import {
  DEFAULT_MODEL_CAPABILITIES,
  ModelCapabilities,
  ModelConfig,
  ModelProvider,
} from '../ModelConfig';

/**
 * Default capabilities for Anthropic Claude models.
 * Anthropic models feature excellent prompt caching with 90% cost savings.
 */
const ANTHROPIC_DEFAULT_CAPABILITIES: ModelCapabilities = {
  ...DEFAULT_MODEL_CAPABILITIES,
  supportsPromptCaching: true,
  cacheDiscountFactor: 0.1,
  supportsTokenCounting: true,
  supportsVision: true,
  supportsNativePdf: true,
  supportsNativeMCPServer: false,
  supportsNativeWebSearch: false,
  supportsDynamicFilteringWebSearch: false,
  supportsNativeCodeExecution: false,
};

/**
 * Anthropic Claude model configurations.
 * Includes Claude 4.x, 3.x Opus, Sonnet, and Haiku variants.
 */
export const ANTHROPIC_MODELS: Record<string, ModelConfig> = {
  opus46T: {
    name: 'opus46T',
    fullName: 'claude-opus-4-6',
    shortName: 'claude-opus-4-6',
    openrouterFullName: 'anthropic/claude-opus-4.6',
    provider: ModelProvider.ANTHROPIC,
    maxOutputTokens: 128000,
    contextWindow: 1000000,
    inputPrice: 5.0,
    outputPrice: 25.0,
    capabilities: {
      ...ANTHROPIC_DEFAULT_CAPABILITIES,
      supportsNativeMCPServer: true,
      supportsNativeWebSearch: true,
      supportsDynamicFilteringWebSearch: true,
      supportsNativeCodeExecution: true,
      supportsAssistantPrefill: false,
      supportsReasoning: true,
      supportsInterleavedThinking: true,
    },
    openRouterOnly: false,
    description: 'Most capable Anthropic model with extended thinking. Excels at complex reasoning, agentic coding, multi-step analysis, and advanced math/science. 1M context window with interleaved thinking.',
  },
  opus46: {
    name: 'opus46',
    fullName: 'claude-opus-4-6',
    shortName: 'claude-opus-4-6',
    openrouterFullName: 'anthropic/claude-opus-4.6',
    provider: ModelProvider.ANTHROPIC,
    maxOutputTokens: 128000,
    contextWindow: 1000000,
    inputPrice: 5.0,
    outputPrice: 25.0,
    capabilities: {
      ...ANTHROPIC_DEFAULT_CAPABILITIES,
      supportsNativeWebSearch: true,
      supportsDynamicFilteringWebSearch: true,
      supportsNativeCodeExecution: true,
      supportsAssistantPrefill: false,
      supportsReasoning: false,
    },
    openRouterOnly: false,
    description: 'Most capable Anthropic model without extended thinking. Ideal for complex tasks requiring deep knowledge, nuanced writing, and sophisticated code generation. 1M context window.',
  },
  sonnet46T: {
    name: 'sonnet46T',
    fullName: 'claude-sonnet-4-6',
    shortName: 'claude-sonnet-4-6',
    openrouterFullName: 'anthropic/claude-sonnet-4.6',
    provider: ModelProvider.ANTHROPIC,
    maxOutputTokens: 64000,
    contextWindow: 1000000,
    inputPrice: 3.0,
    outputPrice: 15.0,
    capabilities: {
      ...ANTHROPIC_DEFAULT_CAPABILITIES,
      supportsNativeWebSearch: true,
      supportsDynamicFilteringWebSearch: true,
      supportsNativeCodeExecution: true,
      supportsAssistantPrefill: false,
      supportsReasoning: true,
      supportsInterleavedThinking: true,
    },
    openRouterOnly: false,
    description: 'High-performance model with extended thinking. Best balance of capability and cost for coding, analysis, and reasoning tasks. 1M context window with interleaved thinking.',
  },
  sonnet46: {
    name: 'sonnet46',
    fullName: 'claude-sonnet-4-6',
    shortName: 'claude-sonnet-4-6',
    openrouterFullName: 'anthropic/claude-sonnet-4.6',
    provider: ModelProvider.ANTHROPIC,
    maxOutputTokens: 64000,
    contextWindow: 1000000,
    inputPrice: 3.0,
    outputPrice: 15.0,
    capabilities: {
      ...ANTHROPIC_DEFAULT_CAPABILITIES,
      supportsNativeWebSearch: true,
      supportsDynamicFilteringWebSearch: true,
      supportsNativeCodeExecution: true,
      supportsAssistantPrefill: true,
      supportsReasoning: false,
    },
    openRouterOnly: false,
    description: 'High-performance model for everyday tasks. Excellent for coding, writing, and analysis with fast response times. 1M context window with assistant prefill support.',
  },
  opus45T: {
    name: 'opus45T',
    fullName: 'claude-opus-4-5',
    shortName: 'claude-opus-4-5',
    openrouterFullName: 'anthropic/claude-opus-4.5',
    provider: ModelProvider.ANTHROPIC,
    maxOutputTokens: 64000,
    contextWindow: 200000,
    inputPrice: 5.0,
    outputPrice: 25.0,
    capabilities: {
      ...ANTHROPIC_DEFAULT_CAPABILITIES,
      supportsNativeMCPServer: true,
      supportsNativeWebSearch: true,
      supportsNativeCodeExecution: true,
      supportsAssistantPrefill: false,
      supportsReasoning: true,
      supportsInterleavedThinking: true,
    },
    openRouterOnly: false,
    deprecated: true,
    description: 'Previous-gen flagship with extended thinking. Strong at complex reasoning and agentic coding tasks. 200K context.',
  },
  opus45: {
    name: 'opus45',
    fullName: 'claude-opus-4-5',
    shortName: 'claude-opus-4-5',
    openrouterFullName: 'anthropic/claude-opus-4.5',
    provider: ModelProvider.ANTHROPIC,
    maxOutputTokens: 64000,
    contextWindow: 200000,
    inputPrice: 5.0,
    outputPrice: 25.0,
    capabilities: {
      ...ANTHROPIC_DEFAULT_CAPABILITIES,
      supportsNativeWebSearch: true,
      supportsNativeCodeExecution: true,
      supportsAssistantPrefill: true,
      supportsReasoning: false,
    },
    openRouterOnly: false,
    deprecated: true,
    description: 'Previous-gen flagship without extended thinking. Strong at complex tasks, writing, and code generation. 200K context.',
  },
  opus41T: {
    name: 'opus41T',
    fullName: 'claude-opus-4-1-20250805',
    shortName: 'claude-opus-4-1',
    openrouterFullName: 'anthropic/claude-opus-4.1',
    provider: ModelProvider.ANTHROPIC,
    maxOutputTokens: 32000,
    contextWindow: 200000,
    inputPrice: 15.0,
    outputPrice: 75.0,
    capabilities: {
      ...ANTHROPIC_DEFAULT_CAPABILITIES,
      supportsNativeMCPServer: true,
      supportsNativeWebSearch: true,
      supportsNativeCodeExecution: true,
      supportsAssistantPrefill: false,
      supportsReasoning: true,
      supportsInterleavedThinking: true,
    },
    openRouterOnly: false,
    deprecated: true,
    description: 'Legacy flagship with extended thinking. Powerful reasoning and agentic capabilities. 200K context.',
  },
  opus41: {
    name: 'opus41',
    fullName: 'claude-opus-4-1-20250805',
    shortName: 'claude-opus-4-1',
    openrouterFullName: 'anthropic/claude-opus-4.1',
    provider: ModelProvider.ANTHROPIC,
    maxOutputTokens: 32000,
    contextWindow: 200000,
    inputPrice: 15.0,
    outputPrice: 75.0,
    capabilities: {
      ...ANTHROPIC_DEFAULT_CAPABILITIES,
      supportsNativeWebSearch: true,
      supportsNativeCodeExecution: true,
      supportsAssistantPrefill: true,
      supportsReasoning: false,
    },
    openRouterOnly: false,
    deprecated: true,
    description: 'Legacy flagship without extended thinking. Strong general-purpose capabilities. 200K context.',
  },
  opus4T: {
    name: 'opus4T',
    fullName: 'claude-opus-4-20250514',
    shortName: 'claude-opus-4',
    openrouterFullName: 'anthropic/claude-opus-4',
    provider: ModelProvider.ANTHROPIC,
    maxOutputTokens: 32000,
    contextWindow: 200000,
    inputPrice: 15.0,
    outputPrice: 75.0,
    capabilities: {
      ...ANTHROPIC_DEFAULT_CAPABILITIES,
      supportsNativeMCPServer: true,
      supportsNativeWebSearch: true,
      supportsNativeCodeExecution: true,
      supportsAssistantPrefill: false,
      supportsReasoning: true,
      supportsInterleavedThinking: true,
    },
    openRouterOnly: false,
    deprecated: true,
    description: 'Original Opus 4 with extended thinking. First-gen flagship reasoning model. 200K context.',
  },
  opus4: {
    name: 'opus4',
    fullName: 'claude-opus-4-20250514',
    shortName: 'claude-opus-4',
    openrouterFullName: 'anthropic/claude-opus-4',
    provider: ModelProvider.ANTHROPIC,
    maxOutputTokens: 32000,
    contextWindow: 200000,
    inputPrice: 15.0,
    outputPrice: 75.0,
    capabilities: {
      ...ANTHROPIC_DEFAULT_CAPABILITIES,
      supportsNativeWebSearch: true,
      supportsNativeCodeExecution: true,
      supportsAssistantPrefill: true,
      supportsReasoning: false,
    },
    openRouterOnly: false,
    deprecated: true,
    description: 'Original Opus 4 without extended thinking. First-gen flagship model. 200K context.',
  },
  sonnet45T: {
    name: 'sonnet45T',
    fullName: 'claude-sonnet-4-5',
    shortName: 'claude-sonnet-4-5',
    openrouterFullName: 'anthropic/claude-sonnet-4.5:thinking',
    provider: ModelProvider.ANTHROPIC,
    maxOutputTokens: 64000,
    contextWindow: 200000,
    inputPrice: 3.0,
    outputPrice: 15.0,
    capabilities: {
      ...ANTHROPIC_DEFAULT_CAPABILITIES,
      supportsNativeWebSearch: true,
      supportsNativeCodeExecution: true,
      supportsAssistantPrefill: false,
      supportsReasoning: true,
      supportsInterleavedThinking: true,
    },
    openRouterOnly: false,
    deprecated: true,
    description: 'Previous-gen Sonnet with extended thinking. Great balance of speed and reasoning capability. 200K context.',
  },
  sonnet45: {
    name: 'sonnet45',
    fullName: 'claude-sonnet-4-5',
    shortName: 'claude-sonnet-4-5',
    openrouterFullName: 'anthropic/claude-sonnet-4.5',
    provider: ModelProvider.ANTHROPIC,
    maxOutputTokens: 64000,
    contextWindow: 200000,
    inputPrice: 3.0,
    outputPrice: 15.0,
    capabilities: {
      ...ANTHROPIC_DEFAULT_CAPABILITIES,
      supportsNativeWebSearch: true,
      supportsNativeCodeExecution: true,
      supportsAssistantPrefill: true,
      supportsReasoning: false,
    },
    openRouterOnly: false,
    deprecated: true,
    description: 'Previous-gen Sonnet without extended thinking. Fast and capable for everyday coding and writing tasks. 200K context.',
  },
  haiku45T: {
    name: 'haiku45T',
    fullName: 'claude-haiku-4-5-20251001',
    shortName: 'claude-haiku-4-5',
    openrouterFullName: 'anthropic/claude-haiku-4.5',
    provider: ModelProvider.ANTHROPIC,
    maxOutputTokens: 64000,
    contextWindow: 200000,
    inputPrice: 1.0,
    outputPrice: 5.0,
    capabilities: {
      ...ANTHROPIC_DEFAULT_CAPABILITIES,
      supportsNativeWebSearch: true,
      supportsNativeCodeExecution: true,
      supportsAssistantPrefill: false,
      supportsReasoning: true,
      supportsInterleavedThinking: true,
    },
    openRouterOnly: false,
    description: 'Fast, affordable model with extended thinking. Ideal for high-volume reasoning tasks, quick subagent work, and cost-sensitive workflows. 200K context.',
  },
  haiku45: {
    name: 'haiku45',
    fullName: 'claude-haiku-4-5-20251001',
    shortName: 'claude-haiku-4-5',
    openrouterFullName: 'anthropic/claude-haiku-4.5',
    provider: ModelProvider.ANTHROPIC,
    maxOutputTokens: 64000,
    contextWindow: 200000,
    inputPrice: 1.0,
    outputPrice: 5.0,
    capabilities: {
      ...ANTHROPIC_DEFAULT_CAPABILITIES,
      supportsNativeWebSearch: true,
      supportsNativeCodeExecution: true,
      supportsAssistantPrefill: true,
      supportsReasoning: false,
    },
    openRouterOnly: false,
    description: 'Fast, affordable model for lightweight tasks. Best for high-volume operations, classification, extraction, and cost-efficient subagent workflows. 200K context.',
  },
  sonnet4T: {
    name: 'sonnet4T',
    fullName: 'claude-sonnet-4-20250514',
    shortName: 'claude-sonnet-4',
    openrouterFullName: 'anthropic/claude-sonnet-4',
    provider: ModelProvider.ANTHROPIC,
    maxOutputTokens: 64000,
    contextWindow: 200000,
    inputPrice: 5.0,
    outputPrice: 25.0,
    capabilities: {
      ...ANTHROPIC_DEFAULT_CAPABILITIES,
      supportsNativeWebSearch: true,
      supportsNativeCodeExecution: true,
      supportsAssistantPrefill: false,
      supportsReasoning: true,
      supportsInterleavedThinking: true,
    },
    openRouterOnly: false,
    deprecated: true,
    description: 'Legacy Sonnet 4 with extended thinking. Reliable reasoning and coding model. 200K context.',
  },
  sonnet4: {
    name: 'sonnet4',
    fullName: 'claude-sonnet-4-20250514',
    shortName: 'claude-sonnet-4',
    openrouterFullName: 'anthropic/claude-sonnet-4',
    provider: ModelProvider.ANTHROPIC,
    maxOutputTokens: 64000,
    contextWindow: 200000,
    inputPrice: 3.0,
    outputPrice: 15.0,
    capabilities: {
      ...ANTHROPIC_DEFAULT_CAPABILITIES,
      supportsNativeWebSearch: true,
      supportsNativeCodeExecution: true,
      supportsAssistantPrefill: true,
      supportsReasoning: false,
    },
    openRouterOnly: false,
    deprecated: true,
    description: 'Legacy Sonnet 4 without extended thinking. Solid general-purpose coding and writing model. 200K context.',
  },
  sonnet37T: {
    name: 'sonnet37T',
    fullName: 'claude-3-7-sonnet-20250219',
    shortName: 'claude-3-7-sonnet',
    openrouterFullName: 'anthropic/claude-3.7-sonnet:thinking',
    provider: ModelProvider.ANTHROPIC,
    maxOutputTokens: 64000,
    contextWindow: 200000,
    inputPrice: 3.0,
    outputPrice: 15.0,
    capabilities: {
      ...ANTHROPIC_DEFAULT_CAPABILITIES,
      supportsNativeWebSearch: true,
      supportsNativeCodeExecution: true,
      supportsAssistantPrefill: false,
      supportsReasoning: true,
    },
    openRouterOnly: false,
    deprecated: true,
    description: 'Legacy Sonnet 3.7 with extended thinking. Early reasoning-capable Sonnet. 200K context.',
  },
  sonnet37: {
    name: 'sonnet37',
    fullName: 'claude-3-7-sonnet-20250219',
    shortName: 'claude-3-7-sonnet',
    openrouterFullName: 'anthropic/claude-3.7-sonnet',
    provider: ModelProvider.ANTHROPIC,
    maxOutputTokens: 64000,
    contextWindow: 200000,
    inputPrice: 3.0,
    outputPrice: 15.0,
    capabilities: {
      ...ANTHROPIC_DEFAULT_CAPABILITIES,
      supportsNativeWebSearch: true,
      supportsNativeCodeExecution: true,
      supportsAssistantPrefill: true,
      supportsReasoning: false,
    },
    openRouterOnly: false,
    deprecated: true,
    description: 'Legacy Sonnet 3.7. Reliable general-purpose model. 200K context.',
  },
  opus3: {
    name: 'opus3',
    fullName: 'claude-3-opus-20240229',
    shortName: 'claude-3-opus',
    openrouterFullName: 'anthropic/claude-3-opus:beta',
    provider: ModelProvider.ANTHROPIC,
    maxOutputTokens: 4096,
    contextWindow: 200000,
    inputPrice: 15.0,
    outputPrice: 75.0,
    capabilities: {
      ...ANTHROPIC_DEFAULT_CAPABILITIES,
      supportsAssistantPrefill: true,
      supportsReasoning: false,
    },
    openRouterOnly: false,
    deprecated: true,
    description: 'Original Claude 3 Opus. Legacy flagship model for complex tasks. 200K context, 4K max output.',
  },
  sonnet36: {
    name: 'sonnet36',
    fullName: 'claude-3-5-sonnet-20241022',
    shortName: 'claude-3-5-sonnet',
    openrouterFullName: 'anthropic/claude-3.5-sonnet:beta',
    provider: ModelProvider.ANTHROPIC,
    maxOutputTokens: 8192,
    contextWindow: 200000,
    inputPrice: 3.0,
    outputPrice: 15.0,
    capabilities: {
      ...ANTHROPIC_DEFAULT_CAPABILITIES,
      supportsAssistantPrefill: true,
      supportsReasoning: false,
    },
    openRouterOnly: false,
    deprecated: true,
    description: 'Claude 3.5 Sonnet (v2). Strong coding and analysis capabilities. 200K context, 8K max output.',
  },
  sonnet35: {
    name: 'sonnet35',
    fullName: 'claude-3-5-sonnet-20240620',
    shortName: 'claude-3-5-sonnet',
    openrouterFullName: 'anthropic/claude-3.5-sonnet-20240620:beta',
    provider: ModelProvider.ANTHROPIC,
    maxOutputTokens: 8192,
    contextWindow: 200000,
    inputPrice: 3.0,
    outputPrice: 15.0,
    capabilities: {
      ...ANTHROPIC_DEFAULT_CAPABILITIES,
      supportsNativeWebSearch: true,
      supportsAssistantPrefill: true,
      supportsReasoning: false,
    },
    openRouterOnly: false,
    deprecated: true,
    description: 'Claude 3.5 Sonnet (v1). Original 3.5 Sonnet release. 200K context, 8K max output.',
  },
  sonnet3: {
    name: 'sonnet3',
    fullName: 'claude-3-sonnet-20240229',
    shortName: 'claude-3-sonnet',
    openrouterFullName: 'anthropic/claude-3.5-sonnet-20240229:beta',
    provider: ModelProvider.ANTHROPIC,
    maxOutputTokens: 8192,
    contextWindow: 200000,
    inputPrice: 3.0,
    outputPrice: 15.0,
    capabilities: {
      ...ANTHROPIC_DEFAULT_CAPABILITIES,
      supportsAssistantPrefill: true,
      supportsReasoning: false,
    },
    openRouterOnly: false,
    deprecated: true,
    description: 'Original Claude 3 Sonnet. Legacy mid-tier model. 200K context, 8K max output.',
  },
  haiku35: {
    name: 'haiku35',
    fullName: 'claude-3-5-haiku-20241022',
    shortName: 'claude-3-5-haiku',
    openrouterFullName: 'anthropic/claude-3.5-haiku:beta',
    provider: ModelProvider.ANTHROPIC,
    maxOutputTokens: 8192,
    contextWindow: 200000,
    inputPrice: 0.8,
    outputPrice: 4.0,
    capabilities: {
      ...ANTHROPIC_DEFAULT_CAPABILITIES,
      supportsNativeWebSearch: true,
      supportsNativeCodeExecution: true,
      supportsAssistantPrefill: true,
      supportsReasoning: false,
      supportsVision: true,
    },
    openRouterOnly: false,
    deprecated: true,
    description: 'Claude 3.5 Haiku. Fast and affordable for high-volume tasks. 200K context, 8K max output.',
  },
  haiku3: {
    name: 'haiku3',
    fullName: 'claude-3-haiku-20240307',
    shortName: 'claude-3-haiku',
    openrouterFullName: 'anthropic/claude-3.5-haiku-20240307:beta',
    provider: ModelProvider.ANTHROPIC,
    maxOutputTokens: 8192,
    contextWindow: 200000,
    inputPrice: 0.25,
    outputPrice: 1.25,
    capabilities: {
      ...ANTHROPIC_DEFAULT_CAPABILITIES,
      supportsAssistantPrefill: true,
      supportsReasoning: false,
    },
    openRouterOnly: false,
    deprecated: true,
    description: 'Original Claude 3 Haiku. Ultra-fast, lowest cost option. 200K context, 8K max output.',
  },
};
