import {
  DEFAULT_MODEL_CAPABILITIES,
  ModelCapabilities,
  ModelConfig,
  ModelProvider,
} from '../ModelConfig';

/**
 * Default capabilities for Anthropic Claude models.
 * Anthropic models feature excellent prompt caching with 90% cost savings.
 */
const ANTHROPIC_DEFAULT_CAPABILITIES: ModelCapabilities = {
  ...DEFAULT_MODEL_CAPABILITIES,
  supportsPromptCaching: true,
  cacheDiscountFactor: 0.1,
  supportsTokenCounting: true,
  supportsVision: true,
  supportsNativePdf: true,
  supportsNativeMCPServer: false,
  supportsNativeWebSearch: false,
  supportsDynamicFilteringWebSearch: false,
  supportsNativeCodeExecution: false,
};

/**
 * Anthropic Claude model configurations.
 * Includes Claude 4.x, 3.x Opus, Sonnet, and Haiku variants.
 */
export const ANTHROPIC_MODELS: Record<string, ModelConfig> = {
  opus46T: {
    name: 'opus46T',
    label: 'Opus 4.6 (Thinking)',
    fullName: 'claude-opus-4-6',
    shortName: 'claude-opus-4-6',
    openrouterFullName: 'anthropic/claude-opus-4.6',
    provider: ModelProvider.ANTHROPIC,
    maxOutputTokens: 128000,
    contextWindow: 1000000,
    inputPrice: 5.0,
    outputPrice: 25.0,
    capabilities: {
      ...ANTHROPIC_DEFAULT_CAPABILITIES,
      supportsNativeMCPServer: true,
      supportsNativeWebSearch: true,
      supportsDynamicFilteringWebSearch: true,
      supportsNativeCodeExecution: true,
      supportsAssistantPrefill: false,
      supportsReasoning: true,
      supportsInterleavedThinking: true,
    },
    openRouterOnly: false,
  },
  opus46: {
    name: 'opus46',
    label: 'Opus 4.6',
    fullName: 'claude-opus-4-6',
    shortName: 'claude-opus-4-6',
    openrouterFullName: 'anthropic/claude-opus-4.6',
    provider: ModelProvider.ANTHROPIC,
    maxOutputTokens: 128000,
    contextWindow: 1000000,
    inputPrice: 5.0,
    outputPrice: 25.0,
    capabilities: {
      ...ANTHROPIC_DEFAULT_CAPABILITIES,
      supportsNativeWebSearch: true,
      supportsDynamicFilteringWebSearch: true,
      supportsNativeCodeExecution: true,
      supportsAssistantPrefill: false,
      supportsReasoning: false,
    },
    openRouterOnly: false,
  },
  sonnet46T: {
    name: 'sonnet46T',
    label: 'Sonnet 4.6 (Thinking)',
    fullName: 'claude-sonnet-4-6',
    shortName: 'claude-sonnet-4-6',
    openrouterFullName: 'anthropic/claude-sonnet-4.6',
    provider: ModelProvider.ANTHROPIC,
    maxOutputTokens: 64000,
    contextWindow: 1000000,
    inputPrice: 3.0,
    outputPrice: 15.0,
    capabilities: {
      ...ANTHROPIC_DEFAULT_CAPABILITIES,
      supportsNativeWebSearch: true,
      supportsDynamicFilteringWebSearch: true,
      supportsNativeCodeExecution: true,
      supportsAssistantPrefill: false,
      supportsReasoning: true,
      supportsInterleavedThinking: true,
    },
    openRouterOnly: false,
  },
  sonnet46: {
    name: 'sonnet46',
    label: 'Sonnet 4.6',
    fullName: 'claude-sonnet-4-6',
    shortName: 'claude-sonnet-4-6',
    openrouterFullName: 'anthropic/claude-sonnet-4.6',
    provider: ModelProvider.ANTHROPIC,
    maxOutputTokens: 64000,
    contextWindow: 1000000,
    inputPrice: 3.0,
    outputPrice: 15.0,
    capabilities: {
      ...ANTHROPIC_DEFAULT_CAPABILITIES,
      supportsNativeWebSearch: true,
      supportsDynamicFilteringWebSearch: true,
      supportsNativeCodeExecution: true,
      supportsAssistantPrefill: true,
      supportsReasoning: false,
    },
    openRouterOnly: false,
  },
  opus45T: {
    name: 'opus45T',
    label: 'Opus 4.5 (Thinking)',
    fullName: 'claude-opus-4-5',
    shortName: 'claude-opus-4-5',
    openrouterFullName: 'anthropic/claude-opus-4.5',
    provider: ModelProvider.ANTHROPIC,
    maxOutputTokens: 64000,
    contextWindow: 200000,
    inputPrice: 5.0,
    outputPrice: 25.0,
    capabilities: {
      ...ANTHROPIC_DEFAULT_CAPABILITIES,
      supportsNativeMCPServer: true,
      supportsNativeWebSearch: true,
      supportsNativeCodeExecution: true,
      supportsAssistantPrefill: false,
      supportsReasoning: true,
      supportsInterleavedThinking: true,
    },
    openRouterOnly: false,
    deprecated: true,
  },
  opus45: {
    name: 'opus45',
    label: 'Opus 4.5',
    fullName: 'claude-opus-4-5',
    shortName: 'claude-opus-4-5',
    openrouterFullName: 'anthropic/claude-opus-4.5',
    provider: ModelProvider.ANTHROPIC,
    maxOutputTokens: 64000,
    contextWindow: 200000,
    inputPrice: 5.0,
    outputPrice: 25.0,
    capabilities: {
      ...ANTHROPIC_DEFAULT_CAPABILITIES,
      supportsNativeWebSearch: true,
      supportsNativeCodeExecution: true,
      supportsAssistantPrefill: true,
      supportsReasoning: false,
    },
    openRouterOnly: false,
    deprecated: true,
  },
  opus41T: {
    name: 'opus41T',
    label: 'Opus 4.1 (Thinking)',
    fullName: 'claude-opus-4-1-20250805',
    shortName: 'claude-opus-4-1',
    openrouterFullName: 'anthropic/claude-opus-4.1',
    provider: ModelProvider.ANTHROPIC,
    maxOutputTokens: 32000,
    contextWindow: 200000,
    inputPrice: 15.0,
    outputPrice: 75.0,
    capabilities: {
      ...ANTHROPIC_DEFAULT_CAPABILITIES,
      supportsNativeMCPServer: true,
      supportsNativeWebSearch: true,
      supportsNativeCodeExecution: true,
      supportsAssistantPrefill: false,
      supportsReasoning: true,
      supportsInterleavedThinking: true,
    },
    openRouterOnly: false,
    deprecated: true,
  },
  opus41: {
    name: 'opus41',
    label: 'Opus 4.1',
    fullName: 'claude-opus-4-1-20250805',
    shortName: 'claude-opus-4-1',
    openrouterFullName: 'anthropic/claude-opus-4.1',
    provider: ModelProvider.ANTHROPIC,
    maxOutputTokens: 32000,
    contextWindow: 200000,
    inputPrice: 15.0,
    outputPrice: 75.0,
    capabilities: {
      ...ANTHROPIC_DEFAULT_CAPABILITIES,
      supportsNativeWebSearch: true,
      supportsNativeCodeExecution: true,
      supportsAssistantPrefill: true,
      supportsReasoning: false,
    },
    openRouterOnly: false,
    deprecated: true,
  },
  opus4T: {
    name: 'opus4T',
    label: 'Opus 4 (Thinking)',
    fullName: 'claude-opus-4-20250514',
    shortName: 'claude-opus-4',
    openrouterFullName: 'anthropic/claude-opus-4',
    provider: ModelProvider.ANTHROPIC,
    maxOutputTokens: 32000,
    contextWindow: 200000,
    inputPrice: 15.0,
    outputPrice: 75.0,
    capabilities: {
      ...ANTHROPIC_DEFAULT_CAPABILITIES,
      supportsNativeMCPServer: true,
      supportsNativeWebSearch: true,
      supportsNativeCodeExecution: true,
      supportsAssistantPrefill: false,
      supportsReasoning: true,
      supportsInterleavedThinking: true,
    },
    openRouterOnly: false,
    deprecated: true,
  },
  opus4: {
    name: 'opus4',
    label: 'Opus 4',
    fullName: 'claude-opus-4-20250514',
    shortName: 'claude-opus-4',
    openrouterFullName: 'anthropic/claude-opus-4',
    provider: ModelProvider.ANTHROPIC,
    maxOutputTokens: 32000,
    contextWindow: 200000,
    inputPrice: 15.0,
    outputPrice: 75.0,
    capabilities: {
      ...ANTHROPIC_DEFAULT_CAPABILITIES,
      supportsNativeWebSearch: true,
      supportsNativeCodeExecution: true,
      supportsAssistantPrefill: true,
      supportsReasoning: false,
    },
    openRouterOnly: false,
    deprecated: true,
  },
  sonnet45T: {
    name: 'sonnet45T',
    label: 'Sonnet 4.5 (Thinking)',
    fullName: 'claude-sonnet-4-5',
    shortName: 'claude-sonnet-4-5',
    openrouterFullName: 'anthropic/claude-sonnet-4.5',
    provider: ModelProvider.ANTHROPIC,
    maxOutputTokens: 64000,
    contextWindow: 200000,
    inputPrice: 3.0,
    outputPrice: 15.0,
    capabilities: {
      ...ANTHROPIC_DEFAULT_CAPABILITIES,
      supportsNativeWebSearch: true,
      supportsNativeCodeExecution: true,
      supportsAssistantPrefill: false,
      supportsReasoning: true,
      supportsInterleavedThinking: true,
    },
    openRouterOnly: false,
    deprecated: true,
  },
  sonnet45: {
    name: 'sonnet45',
    label: 'Sonnet 4.5',
    fullName: 'claude-sonnet-4-5',
    shortName: 'claude-sonnet-4-5',
    openrouterFullName: 'anthropic/claude-sonnet-4.5',
    provider: ModelProvider.ANTHROPIC,
    maxOutputTokens: 64000,
    contextWindow: 200000,
    inputPrice: 3.0,
    outputPrice: 15.0,
    capabilities: {
      ...ANTHROPIC_DEFAULT_CAPABILITIES,
      supportsNativeWebSearch: true,
      supportsNativeCodeExecution: true,
      supportsAssistantPrefill: true,
      supportsReasoning: false,
    },
    openRouterOnly: false,
    deprecated: true,
  },
  haiku45T: {
    name: 'haiku45T',
    label: 'Haiku 4.5 (Thinking)',
    fullName: 'claude-haiku-4-5-20251001',
    shortName: 'claude-haiku-4-5',
    openrouterFullName: 'anthropic/claude-haiku-4.5',
    provider: ModelProvider.ANTHROPIC,
    maxOutputTokens: 64000,
    contextWindow: 200000,
    inputPrice: 1.0,
    outputPrice: 5.0,
    capabilities: {
      ...ANTHROPIC_DEFAULT_CAPABILITIES,
      supportsNativeWebSearch: true,
      supportsNativeCodeExecution: true,
      supportsAssistantPrefill: false,
      supportsReasoning: true,
      supportsInterleavedThinking: true,
    },
    openRouterOnly: false,
  },
  haiku45: {
    name: 'haiku45',
    label: 'Haiku 4.5',
    fullName: 'claude-haiku-4-5-20251001',
    shortName: 'claude-haiku-4-5',
    openrouterFullName: 'anthropic/claude-haiku-4.5',
    provider: ModelProvider.ANTHROPIC,
    maxOutputTokens: 64000,
    contextWindow: 200000,
    inputPrice: 1.0,
    outputPrice: 5.0,
    capabilities: {
      ...ANTHROPIC_DEFAULT_CAPABILITIES,
      supportsNativeWebSearch: true,
      supportsNativeCodeExecution: true,
      supportsAssistantPrefill: true,
      supportsReasoning: false,
    },
    openRouterOnly: false,
  },
  sonnet4T: {
    name: 'sonnet4T',
    label: 'Sonnet 4 (Thinking)',
    fullName: 'claude-sonnet-4-20250514',
    shortName: 'claude-sonnet-4',
    openrouterFullName: 'anthropic/claude-sonnet-4',
    provider: ModelProvider.ANTHROPIC,
    maxOutputTokens: 64000,
    contextWindow: 200000,
    inputPrice: 5.0,
    outputPrice: 25.0,
    capabilities: {
      ...ANTHROPIC_DEFAULT_CAPABILITIES,
      supportsNativeWebSearch: true,
      supportsNativeCodeExecution: true,
      supportsAssistantPrefill: false,
      supportsReasoning: true,
      supportsInterleavedThinking: true,
    },
    openRouterOnly: false,
    deprecated: true,
  },
  sonnet4: {
    name: 'sonnet4',
    label: 'Sonnet 4',
    fullName: 'claude-sonnet-4-20250514',
    shortName: 'claude-sonnet-4',
    openrouterFullName: 'anthropic/claude-sonnet-4',
    provider: ModelProvider.ANTHROPIC,
    maxOutputTokens: 64000,
    contextWindow: 200000,
    inputPrice: 3.0,
    outputPrice: 15.0,
    capabilities: {
      ...ANTHROPIC_DEFAULT_CAPABILITIES,
      supportsNativeWebSearch: true,
      supportsNativeCodeExecution: true,
      supportsAssistantPrefill: true,
      supportsReasoning: false,
    },
    openRouterOnly: false,
    deprecated: true,
  },
  sonnet37T: {
    name: 'sonnet37T',
    label: 'Sonnet 3.7 (Thinking)',
    fullName: 'claude-3-7-sonnet-20250219',
    shortName: 'claude-3-7-sonnet',
    openrouterFullName: 'anthropic/claude-3.7-sonnet',
    provider: ModelProvider.ANTHROPIC,
    maxOutputTokens: 64000,
    contextWindow: 200000,
    inputPrice: 3.0,
    outputPrice: 15.0,
    capabilities: {
      ...ANTHROPIC_DEFAULT_CAPABILITIES,
      supportsNativeWebSearch: true,
      supportsNativeCodeExecution: true,
      supportsAssistantPrefill: false,
      supportsReasoning: true,
    },
    openRouterOnly: false,
    deprecated: true,
  },
  sonnet37: {
    name: 'sonnet37',
    label: 'Sonnet 3.7',
    fullName: 'claude-3-7-sonnet-20250219',
    shortName: 'claude-3-7-sonnet',
    openrouterFullName: 'anthropic/claude-3.7-sonnet',
    provider: ModelProvider.ANTHROPIC,
    maxOutputTokens: 64000,
    contextWindow: 200000,
    inputPrice: 3.0,
    outputPrice: 15.0,
    capabilities: {
      ...ANTHROPIC_DEFAULT_CAPABILITIES,
      supportsNativeWebSearch: true,
      supportsNativeCodeExecution: true,
      supportsAssistantPrefill: true,
      supportsReasoning: false,
    },
    openRouterOnly: false,
    deprecated: true,
  },
  opus3: {
    name: 'opus3',
    label: 'Opus 3',
    fullName: 'claude-3-opus-20240229',
    shortName: 'claude-3-opus',
    openrouterFullName: 'anthropic/claude-3-opus:beta',
    provider: ModelProvider.ANTHROPIC,
    maxOutputTokens: 4096,
    contextWindow: 200000,
    inputPrice: 15.0,
    outputPrice: 75.0,
    capabilities: {
      ...ANTHROPIC_DEFAULT_CAPABILITIES,
      supportsAssistantPrefill: true,
      supportsReasoning: false,
    },
    openRouterOnly: false,
    deprecated: true,
  },
  sonnet36: {
    name: 'sonnet36',
    label: 'Sonnet 3.6',
    fullName: 'claude-3-5-sonnet-20241022',
    shortName: 'claude-3-5-sonnet',
    openrouterFullName: 'anthropic/claude-3.5-sonnet:beta',
    provider: ModelProvider.ANTHROPIC,
    maxOutputTokens: 8192,
    contextWindow: 200000,
    inputPrice: 3.0,
    outputPrice: 15.0,
    capabilities: {
      ...ANTHROPIC_DEFAULT_CAPABILITIES,
      supportsAssistantPrefill: true,
      supportsReasoning: false,
    },
    openRouterOnly: false,
    deprecated: true,
  },
  sonnet35: {
    name: 'sonnet35',
    label: 'Sonnet 3.5',
    fullName: 'claude-3-5-sonnet-20240620',
    shortName: 'claude-3-5-sonnet',
    openrouterFullName: 'anthropic/claude-3.5-sonnet-20240620:beta',
    provider: ModelProvider.ANTHROPIC,
    maxOutputTokens: 8192,
    contextWindow: 200000,
    inputPrice: 3.0,
    outputPrice: 15.0,
    capabilities: {
      ...ANTHROPIC_DEFAULT_CAPABILITIES,
      supportsNativeWebSearch: true,
      supportsAssistantPrefill: true,
      supportsReasoning: false,
    },
    openRouterOnly: false,
    deprecated: true,
  },
  sonnet3: {
    name: 'sonnet3',
    label: 'Sonnet 3',
    fullName: 'claude-3-sonnet-20240229',
    shortName: 'claude-3-sonnet',
    openrouterFullName: 'anthropic/claude-3.5-sonnet-20240229:beta',
    provider: ModelProvider.ANTHROPIC,
    maxOutputTokens: 8192,
    contextWindow: 200000,
    inputPrice: 3.0,
    outputPrice: 15.0,
    capabilities: {
      ...ANTHROPIC_DEFAULT_CAPABILITIES,
      supportsAssistantPrefill: true,
      supportsReasoning: false,
    },
    openRouterOnly: false,
    deprecated: true,
  },
  haiku35: {
    name: 'haiku35',
    label: 'Haiku 3.5',
    fullName: 'claude-3-5-haiku-20241022',
    shortName: 'claude-3-5-haiku',
    openrouterFullName: 'anthropic/claude-3.5-haiku:beta',
    provider: ModelProvider.ANTHROPIC,
    maxOutputTokens: 8192,
    contextWindow: 200000,
    inputPrice: 0.8,
    outputPrice: 4.0,
    capabilities: {
      ...ANTHROPIC_DEFAULT_CAPABILITIES,
      supportsNativeWebSearch: true,
      supportsNativeCodeExecution: true,
      supportsAssistantPrefill: true,
      supportsReasoning: false,
      supportsVision: true,
    },
    openRouterOnly: false,
    deprecated: true,
  },
  haiku3: {
    name: 'haiku3',
    label: 'Haiku 3',
    fullName: 'claude-3-haiku-20240307',
    shortName: 'claude-3-haiku',
    openrouterFullName: 'anthropic/claude-3.5-haiku-20240307:beta',
    provider: ModelProvider.ANTHROPIC,
    maxOutputTokens: 8192,
    contextWindow: 200000,
    inputPrice: 0.25,
    outputPrice: 1.25,
    capabilities: {
      ...ANTHROPIC_DEFAULT_CAPABILITIES,
      supportsAssistantPrefill: true,
      supportsReasoning: false,
    },
    openRouterOnly: false,
    deprecated: true,
  },
};
