import {
  DEFAULT_MODEL_CAPABILITIES,
  ModelCapabilities,
  ModelConfig,
  ModelProvider,
} from '../ModelConfig';

/**
 * Default capabilities for DeepSeek models.
 * Features automatic prompt caching with 90% cost savings.
 */
const DEEPSEEK_DEFAULT_CAPABILITIES: ModelCapabilities = {
  ...DEFAULT_MODEL_CAPABILITIES,
  supportsAutoPromptCaching: true,
  cacheDiscountFactor: 0.1,
  supportsVision: false,
};

/**
 * DeepSeek model configurations.
 * Includes V4, V3.2, R1, and thinking variants.
 *
 * Model name conventions:
 * - fullName: Model name for native DeepSeek API (e.g., 'deepseek-chat', 'deepseek-reasoner')
 * - openrouterFullName: Model name for OpenRouter API (e.g., 'deepseek/deepseek-v3.2')
 */
export const DEEPSEEK_MODELS: Record<string, ModelConfig> = {
  // DeepSeek-V4-Flash (Non-thinking Mode)
  dsv4f: {
    name: 'dsv4f',
    label: 'DeepSeek V4 Flash',
    fullName: 'deepseek-v4-flash',
    shortName: 'deepseek-v4-flash',
    openrouterFullName: 'deepseek/deepseek-v4-flash',
    provider: ModelProvider.DEEPSEEK,
    maxOutputTokens: 393216,
    contextWindow: 1048576,
    inputPrice: 0.14,
    outputPrice: 0.28,
    capabilities: {
      ...DEEPSEEK_DEFAULT_CAPABILITIES,
      supportsAssistantPrefill: true,
      supportsFunctionCalling: true,
      cacheDiscountFactor: 0.2,
    },
    openRouterOnly: false,
  },
  // DeepSeek-V4-Flash (Thinking Mode)
  dsv4fT: {
    name: 'dsv4fT',
    label: 'DeepSeek V4 Flash (Thinking)',
    fullName: 'deepseek-v4-flash',
    shortName: 'deepseek-v4-flash',
    openrouterFullName: 'deepseek/deepseek-v4-flash',
    provider: ModelProvider.DEEPSEEK,
    maxOutputTokens: 393216,
    contextWindow: 1048576,
    inputPrice: 0.14,
    outputPrice: 0.28,
    capabilities: {
      ...DEEPSEEK_DEFAULT_CAPABILITIES,
      supportsReasoning: true,
      supportsReasoningEffort: false,
      supportsFunctionCalling: true,
      supportsAssistantPrefill: true,
      cacheDiscountFactor: 0.2,
    },
    openRouterOnly: false,
  },
  // DeepSeek-V4-Pro (Non-thinking Mode)
  dsv4p: {
    name: 'dsv4p',
    label: 'DeepSeek V4 Pro',
    fullName: 'deepseek-v4-pro',
    shortName: 'deepseek-v4-pro',
    openrouterFullName: 'deepseek/deepseek-v4-pro',
    provider: ModelProvider.DEEPSEEK,
    maxOutputTokens: 393216,
    contextWindow: 1048576,
    inputPrice: 1.74,
    outputPrice: 3.48,
    capabilities: {
      ...DEEPSEEK_DEFAULT_CAPABILITIES,
      supportsAssistantPrefill: true,
      supportsFunctionCalling: true,
      cacheDiscountFactor: 0.0833,
    },
    openRouterOnly: false,
  },
  // DeepSeek-V4-Pro (Thinking Mode)
  dsv4pT: {
    name: 'dsv4pT',
    label: 'DeepSeek V4 Pro (Thinking)',
    fullName: 'deepseek-v4-pro',
    shortName: 'deepseek-v4-pro',
    openrouterFullName: 'deepseek/deepseek-v4-pro',
    provider: ModelProvider.DEEPSEEK,
    maxOutputTokens: 393216,
    contextWindow: 1048576,
    inputPrice: 1.74,
    outputPrice: 3.48,
    capabilities: {
      ...DEEPSEEK_DEFAULT_CAPABILITIES,
      supportsReasoning: true,
      supportsReasoningEffort: false,
      supportsFunctionCalling: true,
      supportsAssistantPrefill: true,
      cacheDiscountFactor: 0.0833,
    },
    openRouterOnly: false,
  },
  // Legacy alias: deepseek-chat routes to deepseek-v4-flash (non-thinking)
  deepseek: {
    name: 'deepseek',
    label: 'DeepSeek V4 Flash (legacy alias)',
    fullName: 'deepseek-chat',
    shortName: 'deepseek-chat',
    openrouterFullName: 'deepseek/deepseek-v4-flash',
    provider: ModelProvider.DEEPSEEK,
    maxOutputTokens: 393216,
    contextWindow: 1048576,
    inputPrice: 0.14,
    outputPrice: 0.28,
    capabilities: {
      ...DEEPSEEK_DEFAULT_CAPABILITIES,
      supportsAssistantPrefill: true,
      supportsFunctionCalling: true,
      cacheDiscountFactor: 0.2,
    },
    openRouterOnly: false,
    deprecated: true,
  },
  // Legacy alias: deepseek-reasoner routes to deepseek-v4-flash (thinking)
  deepseekT: {
    name: 'deepseekT',
    label: 'DeepSeek V4 Flash (Thinking) (legacy alias)',
    fullName: 'deepseek-reasoner',
    shortName: 'deepseek-reasoner',
    openrouterFullName: 'deepseek/deepseek-v4-flash',
    provider: ModelProvider.DEEPSEEK,
    maxOutputTokens: 393216,
    contextWindow: 1048576,
    inputPrice: 0.14,
    outputPrice: 0.28,
    capabilities: {
      ...DEEPSEEK_DEFAULT_CAPABILITIES,
      supportsReasoning: true,
      supportsReasoningEffort: false,
      supportsFunctionCalling: true,
      supportsAssistantPrefill: true,
      cacheDiscountFactor: 0.2,
    },
    openRouterOnly: false,
    deprecated: true,
  },
  // DeepSeek-V3.2-Speciale (Extended Thinking)
  'deepseekT+': {
    name: 'deepseekT+',
    label: 'DeepSeek Speciale (Thinking)',
    fullName: 'deepseek-reasoner',
    shortName: 'deepseek-reasoner',
    openrouterFullName: 'deepseek/deepseek-v3.2-speciale',
    provider: ModelProvider.DEEPSEEK,
    maxOutputTokens: 131072,
    contextWindow: 163840,
    inputPrice: 0.28,
    outputPrice: 0.42,
    capabilities: {
      ...DEEPSEEK_DEFAULT_CAPABILITIES,
      supportsReasoning: true,
      supportsReasoningEffort: false,
      supportsFunctionCalling: false,
      supportsAssistantPrefill: false,
    },
    openRouterOnly: false,
    baseUrl: 'https://api.deepseek.com/v3.2_speciale_expires_on_20251215',
    deprecated: true,
    retired: true,
  },
  dsv3: {
    name: 'dsv3',
    label: 'DeepSeek V3',
    fullName: 'deepseek-chat',
    shortName: 'deepseek-chat',
    openrouterFullName: 'deepseek/deepseek-chat-v3-0324',
    provider: ModelProvider.DEEPSEEK,
    maxOutputTokens: 64000,
    contextWindow: 128000,
    inputPrice: 0.14,
    outputPrice: 0.28,
    capabilities: {
      ...DEEPSEEK_DEFAULT_CAPABILITIES,
      supportsAssistantPrefill: true,
    },
    openRouterOnly: false,
    deprecated: true,
    retired: true,
  },
  dsr1: {
    name: 'dsr1',
    label: 'DeepSeek R1',
    fullName: 'deepseek-reasoner',
    shortName: 'deepseek-reasoner',
    openrouterFullName: 'deepseek/deepseek-r1-0528',
    provider: ModelProvider.DEEPSEEK,
    maxOutputTokens: 65536,
    contextWindow: 128000,
    inputPrice: 4,
    outputPrice: 4,
    capabilities: {
      ...DEEPSEEK_DEFAULT_CAPABILITIES,
      supportsReasoning: true,
      supportsReasoningEffort: false,
    },
    openRouterOnly: false,
    deprecated: true,
    retired: true,
  },
  dsv3o: {
    name: 'dsv3o',
    label: 'DeepSeek V3 (Old)',
    fullName: 'deepseek-chat',
    shortName: 'deepseek-chat',
    openrouterFullName: 'deepseek/deepseek-chat-v3-0324',
    provider: ModelProvider.DEEPSEEK,
    maxOutputTokens: 8192,
    contextWindow: 64000,
    inputPrice: 0.27,
    outputPrice: 1.1,
    capabilities: {
      ...DEEPSEEK_DEFAULT_CAPABILITIES,
      supportsAssistantPrefill: true,
    },
    openRouterOnly: false,
    deprecated: true,
    retired: true,
  },
  dsr1o: {
    name: 'dsr1o',
    label: 'DeepSeek R1 (Old)',
    fullName: 'deepseek-reasoner',
    shortName: 'deepseek-reasoner',
    openrouterFullName: 'deepseek/deepseek-r1-0528',
    provider: ModelProvider.DEEPSEEK,
    maxOutputTokens: 64000,
    contextWindow: 64000,
    inputPrice: 0.55,
    outputPrice: 2.19,
    capabilities: {
      ...DEEPSEEK_DEFAULT_CAPABILITIES,
      supportsReasoning: true,
      supportsReasoningEffort: false,
    },
    openRouterOnly: false,
    deprecated: true,
    retired: true,
  },
};
