import {
  DEFAULT_MODEL_CAPABILITIES,
  ModelCapabilities,
  ModelEntry,
  ModelProvider,
  ReasoningEffort,
} from '../ModelConfig';

/**
 * Default capabilities for Google Gemini models.
 * Features native PDF, vision, and audio support with 75% cache cost savings.
 *
 * Note: Native web search is disabled because Google's content generation API
 * doesn't support combining googleSearch with functionDeclarations
 * (this is a Live API only feature).
 */
const GOOGLE_DEFAULT_CAPABILITIES: ModelCapabilities = {
  ...DEFAULT_MODEL_CAPABILITIES,
  cacheDiscountFactor: 0.25,
  supportsNativePdf: true,
  supportsVision: true,
  supportsNativeAudio: true,
  supportsNativeMCPServer: false,
  supportsNativeWebSearch: false,
};

/** Gemini 3.x thinking levels (thinking cannot be turned off on 3.x). */
const LOW_TO_HIGH_EFFORTS = [ReasoningEffort.LOW, ReasoningEffort.MEDIUM, ReasoningEffort.HIGH] as const;
const MINIMAL_TO_HIGH_EFFORTS = [ReasoningEffort.MINIMAL, ...LOW_TO_HIGH_EFFORTS] as const;

/**
 * Google Gemini model configurations.
 * Includes Gemini 3.x and 2.5 Pro/Flash variants.
 */
export const GOOGLE_MODELS: readonly ModelEntry[] = [
  {
    label: 'Gemini 3.8 Flash',
    id: 'gemini-3.8-flash',
    shortName: 'gemini-3.8-flash',
    provider: ModelProvider.GOOGLE,
    maxOutputTokens: 65536,
    contextWindow: 1048576,
    inputPrice: 0.75,
    outputPrice: 3.75,
    capabilities: {
      ...GOOGLE_DEFAULT_CAPABILITIES,
      cacheDiscountFactor: 0.1,
      supportsPromptCaching: true,
      supportsAutoPromptCaching: true,
      supportsNativeCodeExecution: true,
      supportsNativeMCPServer: true,
    },
    reasoning: { efforts: LOW_TO_HIGH_EFFORTS, providerDefault: ReasoningEffort.MEDIUM },
    source: { url: 'https://ai.google.dev/gemini-api/docs/thinking', verified: '2026-09-30' },
    legacyKeys: { gemini38f: { effort: ReasoningEffort.MEDIUM } },
    openRouterOnly: false,
  },
  {
    label: 'Gemini 3.7 Flash',
    id: 'gemini-3.7-flash',
    shortName: 'gemini-3.7-flash',
    openrouterFullName: 'google/gemini-3.7-flash',
    provider: ModelProvider.GOOGLE,
    maxOutputTokens: 65536,
    contextWindow: 1048576,
    inputPrice: 0.75,
    outputPrice: 3.75,
    capabilities: {
      ...GOOGLE_DEFAULT_CAPABILITIES,
      cacheDiscountFactor: 0.1,
      supportsPromptCaching: true,
      supportsAutoPromptCaching: true,
      supportsNativeCodeExecution: true,
      supportsNativeMCPServer: true,
    },
    reasoning: { efforts: LOW_TO_HIGH_EFFORTS, providerDefault: ReasoningEffort.MEDIUM },
    source: { url: 'https://ai.google.dev/gemini-api/docs/thinking', verified: '2026-09-30' },
    legacyKeys: { gemini37f: { effort: ReasoningEffort.HIGH } },
    openRouterOnly: false,
    deprecated: true,
  },
  {
    label: 'Gemini 3.6 Flash',
    id: 'gemini-3.6-flash',
    shortName: 'gemini-3.6-flash',
    openrouterFullName: 'google/gemini-3.6-flash',
    vscodeLMFullName: 'gemini-3.6-flash',
    copilotFullName: 'gemini-3.6-flash',
    provider: ModelProvider.GOOGLE,
    maxOutputTokens: 65536,
    contextWindow: 1048576,
    // Same rates as 3.7/3.8 Flash through 2026-12-31 ($0.75 / $0.075 cached /
    // $3.75); $1.50 / $0.15 / $7.50 from 2027-01-01 (ai.google.dev pricing).
    inputPrice: 0.75,
    outputPrice: 3.75,
    capabilities: {
      ...GOOGLE_DEFAULT_CAPABILITIES,
      cacheDiscountFactor: 0.1,
      supportsPromptCaching: true,
      supportsAutoPromptCaching: true,
      supportsNativeCodeExecution: true,
      supportsNativeMCPServer: true,
    },
    reasoning: { efforts: MINIMAL_TO_HIGH_EFFORTS, providerDefault: ReasoningEffort.MEDIUM },
    source: { url: 'https://ai.google.dev/gemini-api/docs/thinking', verified: '2026-09-30' },
    legacyKeys: { gemini36f: { effort: ReasoningEffort.HIGH } },
    openRouterOnly: false,
    deprecated: true,
  },
  {
    label: 'Gemini 3.5 Flash-Lite',
    id: 'gemini-3.5-flash-lite',
    shortName: 'gemini-3.5-flash-lite',
    openrouterFullName: 'google/gemini-3.5-flash-lite',
    provider: ModelProvider.GOOGLE,
    maxOutputTokens: 65536,
    contextWindow: 1048576,
    inputPrice: 0.3,
    outputPrice: 2.5,
    capabilities: {
      ...GOOGLE_DEFAULT_CAPABILITIES,
      cacheDiscountFactor: 0.1,
      supportsPromptCaching: true,
      supportsAutoPromptCaching: true,
      supportsNativeCodeExecution: true,
    },
    reasoning: { efforts: MINIMAL_TO_HIGH_EFFORTS, providerDefault: ReasoningEffort.MINIMAL },
    source: { url: 'https://ai.google.dev/gemini-api/docs/thinking', verified: '2026-09-30' },
    legacyKeys: { 'gemini35f-': { effort: ReasoningEffort.LOW } },
    openRouterOnly: false,
  },
  {
    label: 'Gemini 3.5 Flash',
    id: 'gemini-3.5-flash',
    shortName: 'gemini-3.5-flash',
    openrouterFullName: 'google/gemini-3.5-flash',
    vscodeLMFullName: 'gemini-3.5-flash',
    copilotFullName: 'gemini-3.5-flash',
    provider: ModelProvider.GOOGLE,
    maxOutputTokens: 65536,
    contextWindow: 1048576,
    inputPrice: 1.5,
    outputPrice: 9.0,
    capabilities: {
      ...GOOGLE_DEFAULT_CAPABILITIES,
      cacheDiscountFactor: 0.1,
      supportsPromptCaching: true,
      supportsAutoPromptCaching: true,
      supportsNativeCodeExecution: true,
      supportsNativeMCPServer: true,
    },
    reasoning: { efforts: MINIMAL_TO_HIGH_EFFORTS, providerDefault: ReasoningEffort.MEDIUM },
    source: { url: 'https://ai.google.dev/gemini-api/docs/thinking', verified: '2026-09-30' },
    legacyKeys: { gemini35f: { effort: ReasoningEffort.HIGH } },
    openRouterOnly: false,
    deprecated: true,
  },
  {
    label: 'Gemini 3.1 Pro',
    id: 'gemini-3.1-pro-preview',
    shortName: 'gemini-3.1-pro-preview',
    openrouterFullName: 'google/gemini-3.1-pro-preview',
    vscodeLMFullName: 'gemini-3.1-pro-preview',
    copilotFullName: 'gemini-3.1-pro-preview',
    provider: ModelProvider.GOOGLE,
    maxOutputTokens: 65536,
    contextWindow: 1048576,
    inputPrice: 2.0,
    outputPrice: 12.0,
    longContextPricing: {
      aboveInputTokens: 200_000,
      inputPrice: 4.0,
      outputPrice: 18.0,
      cacheDiscountFactor: 0.1,
    },
    capabilities: {
      ...GOOGLE_DEFAULT_CAPABILITIES,
      cacheDiscountFactor: 0.1,
      supportsPromptCaching: true,
      supportsAutoPromptCaching: true,
      supportsNativeCodeExecution: true,
      supportsNativeMCPServer: true,
    },
    reasoning: { efforts: LOW_TO_HIGH_EFFORTS, providerDefault: ReasoningEffort.HIGH },
    source: { url: 'https://ai.google.dev/gemini-api/docs/thinking', verified: '2026-09-30' },
    legacyKeys: { gemini31p: { effort: ReasoningEffort.HIGH } },
    openRouterOnly: false,
  },
  {
    label: 'Gemini 3.1 Flash-Lite',
    id: 'gemini-3.1-flash-lite',
    shortName: 'gemini-3.1-flash-lite',
    openrouterFullName: 'google/gemini-3.1-flash-lite',
    provider: ModelProvider.GOOGLE,
    maxOutputTokens: 65536,
    contextWindow: 1048576,
    inputPrice: 0.25,
    outputPrice: 1.5,
    capabilities: {
      ...GOOGLE_DEFAULT_CAPABILITIES,
      cacheDiscountFactor: 0.1,
      supportsPromptCaching: true,
      supportsAutoPromptCaching: true,
      supportsNativeCodeExecution: true,
    },
    // Not in the thinking-page table; the Gemini 3 guide lists minimal (default) to high.
    reasoning: { efforts: MINIMAL_TO_HIGH_EFFORTS, providerDefault: ReasoningEffort.MINIMAL },
    source: { url: 'https://ai.google.dev/gemini-api/docs/gemini-3', verified: '2026-09-30' },
    legacyKeys: { 'gemini31f-': { effort: ReasoningEffort.LOW } },
    openRouterOnly: false,
    deprecated: true,
  },
  {
    label: 'Gemini 3 Pro',
    id: 'gemini-3-pro-preview',
    shortName: 'gemini-3-pro-preview',
    openrouterFullName: 'google/gemini-3-pro-preview',
    vscodeLMFullName: 'gemini-3-pro',
    provider: ModelProvider.GOOGLE,
    maxOutputTokens: 65536,
    contextWindow: 1048576,
    inputPrice: 2.0,
    outputPrice: 12.0,
    capabilities: {
      ...GOOGLE_DEFAULT_CAPABILITIES,
      supportsPromptCaching: true,
      supportsAutoPromptCaching: true,
      supportsNativeCodeExecution: true,
      supportsNativeMCPServer: true,
    },
    reasoning: { efforts: [ReasoningEffort.LOW, ReasoningEffort.HIGH], providerDefault: ReasoningEffort.HIGH },
    legacyKeys: { gemini3p: { effort: ReasoningEffort.HIGH } },
    openRouterOnly: false,
    deprecated: true,
    retired: true,
  },
  {
    label: 'Gemini 3 Flash',
    id: 'gemini-3-flash-preview',
    shortName: 'gemini-3-flash-preview',
    openrouterFullName: 'google/gemini-3-flash-preview',
    provider: ModelProvider.GOOGLE,
    maxOutputTokens: 65536,
    contextWindow: 1048576,
    // $0.50 / $0.05 cached / $3.00 (text/image/video; ai.google.dev pricing).
    inputPrice: 0.5,
    outputPrice: 3.0,
    capabilities: {
      ...GOOGLE_DEFAULT_CAPABILITIES,
      cacheDiscountFactor: 0.1,
      supportsPromptCaching: true,
      supportsAutoPromptCaching: true,
      supportsNativeCodeExecution: true,
      supportsNativeMCPServer: true,
    },
    reasoning: { efforts: MINIMAL_TO_HIGH_EFFORTS, providerDefault: ReasoningEffort.HIGH },
    source: { url: 'https://ai.google.dev/gemini-api/docs/thinking', verified: '2026-09-30' },
    legacyKeys: { gemini3f: { effort: ReasoningEffort.HIGH } },
    openRouterOnly: false,
    // Still served as a preview; the deprecations page announces no shutdown
    // date (recommended replacement: gemini-3.6-flash), so not retired.
    deprecated: true,
  },
  {
    label: 'Gemini 2.5 Pro',
    id: 'gemini-2.5-pro',
    shortName: 'gemini-2.5-pro',
    openrouterFullName: 'google/gemini-2.5-pro',
    vscodeLMFullName: 'gemini-2.5-pro',
    provider: ModelProvider.GOOGLE,
    maxOutputTokens: 65536,
    contextWindow: 1048576,
    inputPrice: 1.25,
    outputPrice: 10.0,
    longContextPricing: {
      aboveInputTokens: 200_000,
      inputPrice: 2.5,
      outputPrice: 15.0,
      cacheDiscountFactor: 0.1,
    },
    capabilities: {
      ...GOOGLE_DEFAULT_CAPABILITIES,
      cacheDiscountFactor: 0.1,
      supportsPromptCaching: true,
      supportsAutoPromptCaching: true,
      supportsNativeCodeExecution: true,
      supportsNativeMCPServer: true,
    },
    // 2.5 uses thinking_budget (tokens); thinking cannot be turned off for 2.5 Pro.
    reasoning: { efforts: [], budget: true },
    source: { url: 'https://ai.google.dev/gemini-api/docs/openai', verified: '2026-09-30' },
    legacyKeys: { gemini25p: {} },
    openRouterOnly: false,
    deprecated: true,
  },
  {
    label: 'Gemini 2.5 Flash',
    id: 'gemini-flash-latest',
    shortName: 'gemini-flash-latest',
    openrouterFullName: 'google/gemini-2.5-flash-preview-09-2025',
    provider: ModelProvider.GOOGLE,
    maxOutputTokens: 65536,
    contextWindow: 1048576,
    inputPrice: 0.3,
    outputPrice: 2.5,
    capabilities: {
      ...GOOGLE_DEFAULT_CAPABILITIES,
      cacheDiscountFactor: 0.1,
      supportsPromptCaching: true,
      supportsAutoPromptCaching: true,
      supportsNativeCodeExecution: true,
      supportsNativeMCPServer: true,
    },
    // The alias has pointed to gemini-3.5-flash since 2026-05-19 (release notes).
    reasoning: { efforts: MINIMAL_TO_HIGH_EFFORTS, providerDefault: ReasoningEffort.MEDIUM },
    source: { url: 'https://ai.google.dev/gemini-api/docs/thinking', verified: '2026-09-30' },
    legacyKeys: { gemini25f: {} },
    openRouterOnly: false,
    deprecated: true,
  },
  {
    label: 'Gemini 2.5 Flash (06-17)',
    id: 'gemini-2.5-flash',
    shortName: 'gemini-2.5-flash',
    openrouterFullName: 'google/gemini-2.5-flash',
    provider: ModelProvider.GOOGLE,
    maxOutputTokens: 65536,
    contextWindow: 1048576,
    inputPrice: 0.3,
    outputPrice: 2.5,
    capabilities: {
      ...GOOGLE_DEFAULT_CAPABILITIES,
      cacheDiscountFactor: 0.1,
      supportsPromptCaching: true,
      supportsAutoPromptCaching: true,
      supportsNativeCodeExecution: true,
      supportsNativeMCPServer: true,
    },
    // 2.5 uses thinking_budget (tokens); reasoning_effort 'none' turns thinking off.
    reasoning: { efforts: [], off: [], budget: true },
    source: { url: 'https://ai.google.dev/gemini-api/docs/openai', verified: '2026-09-30' },
    legacyKeys: { gemini25f0617: {} },
    openRouterOnly: false,
    deprecated: true,
  },
  // Gemini 2.5 Flash-Lite (GA, released 2025-07-22). $0.10 / $0.01 cached /
  // $0.40 (text/image/video). Google limits 2.5 access to existing users and
  // points new projects at 3.5 Flash-Lite, so deprecated like its 2.5 siblings.
  {
    label: 'Gemini 2.5 Flash-Lite (07-22)',
    id: 'gemini-2.5-flash-lite',
    shortName: 'gemini-2.5-flash-lite',
    openrouterFullName: 'google/gemini-2.5-flash-lite',
    provider: ModelProvider.GOOGLE,
    maxOutputTokens: 65536,
    contextWindow: 1048576,
    inputPrice: 0.1,
    outputPrice: 0.4,
    capabilities: {
      ...GOOGLE_DEFAULT_CAPABILITIES,
      cacheDiscountFactor: 0.1,
      supportsPromptCaching: true,
      supportsAutoPromptCaching: true,
      supportsNativeCodeExecution: true,
    },
    // 2.5 uses thinking_budget (tokens); thinking is off by default ("Off" in
    // the thinking page's table) and reasoning_effort 'none' keeps it off.
    reasoning: { efforts: [], off: [], budget: true, providerDefault: ReasoningEffort.NONE },
    source: { url: 'https://ai.google.dev/gemini-api/docs/thinking', verified: '2026-09-30' },
    legacyKeys: { 'gemini25f-0722': {} },
    openRouterOnly: false,
    deprecated: true,
  },
  {
    label: 'Gemini 2.5 Flash Lite',
    id: 'gemini-2.5-flash-lite-preview-09-2025',
    shortName: 'gemini-2.5-flash-lite-preview',
    openrouterFullName: 'google/gemini-2.5-flash-lite-preview-09-2025',
    provider: ModelProvider.GOOGLE,
    maxOutputTokens: 32768,
    contextWindow: 65536,
    inputPrice: 0.1,
    outputPrice: 0.4,
    capabilities: {
      ...GOOGLE_DEFAULT_CAPABILITIES,
      supportsPromptCaching: true,
      supportsAutoPromptCaching: true,
      supportsNativeCodeExecution: false,
    },
    reasoning: { efforts: [] },
    legacyKeys: { 'gemini25f-': {} },
    openRouterOnly: false,
    deprecated: true,
    retired: true,
  },
];
