import {
  DEFAULT_MODEL_CAPABILITIES,
  ModelCapabilities,
  ModelConfig,
  ModelProvider,
  ReasoningEffort,
} from '../ModelConfig';

/**
 * Default capabilities for Moonshot (Kimi) models.
 */
const MOONSHOT_DEFAULT_CAPABILITIES: ModelCapabilities = {
  ...DEFAULT_MODEL_CAPABILITIES,
  supportsPromptCaching: false,
  supportsSystemPrompt: true,
};

/**
 * Moonshot AI (Kimi) model configurations.
 * Includes Kimi K2 and thinking variants.
 */
export const MOONSHOT_MODELS: Record<string, ModelConfig> = {
  kimi: {
    name: 'kimi128k',
    label: 'Moonshot V1 128K',
    fullName: 'moonshot-v1-128k',
    shortName: 'moonshot-v1-128k',
    openrouterFullName: 'moonshotai/moonshot-v1-128k',
    provider: ModelProvider.MOONSHOT,
    maxOutputTokens: 64000,
    contextWindow: 131072,
    inputPrice: 2.0,
    outputPrice: 5.0,
    description: 'Moonshot V1 128K, no vision',
    capabilities: {
      ...MOONSHOT_DEFAULT_CAPABILITIES,
      supportsVision: false,
    },
    openRouterOnly: false,
    deprecated: true,
  },
  kimiv: {
    name: 'kimi128kv',
    label: 'Moonshot V1 128K Vision',
    fullName: 'moonshot-v1-128k-vision-preview',
    shortName: 'moonshot-v1-128k-vision-preview',
    openrouterFullName: 'moonshotai/moonshot-v1-128k-vision',
    provider: ModelProvider.MOONSHOT,
    maxOutputTokens: 64000,
    contextWindow: 131072,
    inputPrice: 2.0,
    outputPrice: 5.0,
    description: 'Moonshot V1 128K with vision',
    capabilities: {
      ...MOONSHOT_DEFAULT_CAPABILITIES,
      supportsVision: true,
    },
    openRouterOnly: false,
    deprecated: true,
  },
  kimit: {
    name: 'kimit',
    label: 'Kimi Thinking Preview',
    fullName: 'kimi-thinking-preview',
    shortName: 'kimi-thinking-preview',
    openrouterFullName: 'moonshotai/kimi-thinking-preview',
    provider: ModelProvider.MOONSHOT,
    maxOutputTokens: 64000,
    contextWindow: 128000,
    inputPrice: 0.42,
    outputPrice: 1.68,
    description: 'Kimi thinking preview with vision',
    capabilities: {
      ...MOONSHOT_DEFAULT_CAPABILITIES,
      supportsVision: true,
      supportsReasoning: true,
    },
    openRouterOnly: false,
    deprecated: true,
  },
  kimi2: {
    name: 'kimi2',
    label: 'Kimi K2',
    fullName: 'kimi-k2-0905-preview',
    shortName: 'kimi-k2-preview',
    openrouterFullName: 'moonshotai/kimi-k2-0905',
    provider: ModelProvider.MOONSHOT,
    maxOutputTokens: 64000,
    contextWindow: 262144,
    inputPrice: 0.6,
    outputPrice: 2.5,
    description: 'Kimi K2, 256K context, no reasoning',
    capabilities: {
      ...MOONSHOT_DEFAULT_CAPABILITIES,
      supportsVision: false,
      supportsAutoPromptCaching: true,
      cacheDiscountFactor: 0.25,
      supportsReasoning: false,
    },
    openRouterOnly: false,
    deprecated: true,
  },
  'kimi2+': {
    name: 'kimi2+',
    label: 'Kimi K2 Turbo',
    fullName: 'kimi-k2-turbo-preview',
    shortName: 'kimi-k2-turbo-preview',
    openrouterFullName: 'moonshotai/kimi-k2-turbo',
    provider: ModelProvider.MOONSHOT,
    maxOutputTokens: 64000,
    contextWindow: 262144,
    inputPrice: 1.15,
    outputPrice: 8.0,
    description: 'Kimi K2 Turbo, faster, more expensive',
    capabilities: {
      ...MOONSHOT_DEFAULT_CAPABILITIES,
      supportsVision: false,
      supportsAutoPromptCaching: true,
      cacheDiscountFactor: 0.15 / 1.15,
      supportsReasoning: false,
    },
    openRouterOnly: false,
    deprecated: true,
  },
  kimi2T: {
    name: 'kimi2T',
    label: 'Kimi K2 (Thinking)',
    fullName: 'kimi-k2-thinking',
    shortName: 'kimi-k2-thinking',
    openrouterFullName: 'moonshotai/kimi-k2-thinking',
    provider: ModelProvider.MOONSHOT,
    maxOutputTokens: 64000,
    contextWindow: 262144,
    inputPrice: 0.6,
    outputPrice: 2.5,
    description: 'Kimi K2 with thinking, 256K context',
    capabilities: {
      ...MOONSHOT_DEFAULT_CAPABILITIES,
      supportsVision: false,
      supportsReasoning: true,
      supportsInterleavedThinking: true,
      supportsAutoPromptCaching: true,
      cacheDiscountFactor: 0.25,
      reasoningEffort: ReasoningEffort.HIGH,
    },
    openRouterOnly: false,
    deprecated: true,
  },
  'kimi2T+': {
    name: 'kimi2T+',
    label: 'Kimi K2 Turbo (Thinking)',
    fullName: 'kimi-k2-thinking-turbo',
    shortName: 'kimi-k2-thinking-turbo',
    openrouterFullName: 'moonshotai/kimi-k2-thinking-turbo',
    provider: ModelProvider.MOONSHOT,
    maxOutputTokens: 64000,
    contextWindow: 262144,
    inputPrice: 1.15,
    outputPrice: 8.0,
    description: 'Kimi K2 Thinking Turbo, fast reasoning',
    capabilities: {
      ...MOONSHOT_DEFAULT_CAPABILITIES,
      supportsVision: false,
      supportsReasoning: true,
      supportsInterleavedThinking: true,
      supportsAutoPromptCaching: true,
      cacheDiscountFactor: 0.15 / 1.15,
      reasoningEffort: ReasoningEffort.HIGH,
    },
    openRouterOnly: false,
    deprecated: true,
  },
  // kimi-k2.5: A model that can enable or disable thinking capability, enabled by default. You can disable thinking by using {"type": "disabled"}
  kimi25: {
    name: 'kimi25',
    label: 'Kimi K2.5',
    fullName: 'kimi-k2.5',
    shortName: 'kimi-k2.5',
    openrouterFullName: 'moonshotai/kimi-k2.5',
    provider: ModelProvider.MOONSHOT,
    maxOutputTokens: 64000,
    contextWindow: 262144,
    inputPrice: 0.6,
    outputPrice: 3.0,
    description: 'Latest Kimi K2.5 with vision, 256K context',
    capabilities: {
      ...MOONSHOT_DEFAULT_CAPABILITIES,
      supportsVision: true,
      supportsAutoPromptCaching: true,
      cacheDiscountFactor: 0.1 / 0.6,
    },
    openRouterOnly: false,
  },
  kimi25T: {
    name: 'kimi25T',
    label: 'Kimi K2.5 (Thinking)',
    fullName: 'kimi-k2.5',
    shortName: 'kimi-k2.5',
    openrouterFullName: 'moonshotai/kimi-k2.5',
    provider: ModelProvider.MOONSHOT,
    maxOutputTokens: 64000,
    contextWindow: 262144,
    inputPrice: 0.6,
    outputPrice: 3.0,
    description: 'Kimi K2.5 with thinking and vision, 256K context',
    capabilities: {
      ...MOONSHOT_DEFAULT_CAPABILITIES,
      supportsVision: true,
      supportsReasoning: true,
      supportsInterleavedThinking: true,
      supportsAutoPromptCaching: true,
      cacheDiscountFactor: 0.1 / 0.6,
      reasoningEffort: ReasoningEffort.HIGH,
    },
    openRouterOnly: false,
  },
};
