import {
  DEFAULT_MODEL_CAPABILITIES,
  ModelCapabilities,
  ModelConfig,
  ModelProvider,
  ReasoningEffort,
} from '../ModelConfig';

/**
 * Default capabilities for OpenAI reasoning models (o-series).
 * These models feature extended reasoning with configurable effort levels.
 */
const OPENAI_REASONING_DEFAULT_CAPABILITIES: ModelCapabilities = {
  ...DEFAULT_MODEL_CAPABILITIES,
  supportsAutoPromptCaching: true,
  cacheDiscountFactor: 0.5,
  supportsReasoning: true,
  supportsIntermDevMsgs: true,
  reasoningEffort: ReasoningEffort.HIGH,
  supportsReasoningEffort: true,
};

/**
 * OpenAI reasoning model configurations.
 * Includes o1, o3, o4, and GPT-5 reasoning variants.
 */
export const OPENAI_REASONING_MODELS: Record<string, ModelConfig> = {
  'o4-': {
    name: 'o4-',
    fullName: 'o4-mini-2025-04-16',
    shortName: 'o4-mini',
    openrouterFullName: 'openai/o4-mini-high',
    provider: ModelProvider.OPENAI,
    maxOutputTokens: 100000,
    contextWindow: 200000,
    inputPrice: 1.0,
    outputPrice: 4.4,
    capabilities: {
      ...OPENAI_REASONING_DEFAULT_CAPABILITIES,
      cacheDiscountFactor: 0.25,
      supportsNativeWebSearch: true,
      supportsNativeMCPServer: true,
      supportsNativeCodeExecution: true,
      supportsNativePdf: true,
      supportsVision: true,
    },
    openRouterOnly: false,
    deprecated: true,
    description: 'o4-mini reasoning model. Cost-efficient reasoning with vision and tool use. 200K context.',
  },
  o3pro: {
    name: 'o3pro',
    fullName: 'o3-pro-2025-06-10',
    shortName: 'o3-pro',
    openrouterFullName: 'openai/o3-pro',
    provider: ModelProvider.OPENAI,
    maxOutputTokens: 100000,
    contextWindow: 200000,
    inputPrice: 20.0,
    outputPrice: 80.0,
    capabilities: {
      ...OPENAI_REASONING_DEFAULT_CAPABILITIES,
      supportsNativeWebSearch: true,
      supportsNativeMCPServer: true,
      supportsAutoPromptCaching: false,
      supportsNativePdf: true,
      supportsVision: true,
    },
    openRouterOnly: false,
    deprecated: true,
    description: 'o3-pro premium reasoning model. Maximum reasoning depth for the hardest problems. 200K context.',
  },
  o3: {
    name: 'o3',
    fullName: 'o3-2025-04-16',
    shortName: 'o3',
    openrouterFullName: 'openai/o3',
    provider: ModelProvider.OPENAI,
    maxOutputTokens: 100000,
    contextWindow: 200000,
    inputPrice: 2.0,
    outputPrice: 8.0,
    capabilities: {
      ...OPENAI_REASONING_DEFAULT_CAPABILITIES,
      cacheDiscountFactor: 0.25,
      supportsNativeWebSearch: true,
      supportsNativeMCPServer: true,
      supportsNativeCodeExecution: true,
      supportsNativePdf: true,
      supportsVision: true,
    },
    openRouterOnly: false,
    deprecated: true,
    description: 'o3 reasoning model. Strong math, science, and coding reasoning with tool use. 200K context.',
  },
  'o3-': {
    name: 'o3-',
    fullName: 'o3-mini-2025-01-31',
    shortName: 'o3-mini',
    openrouterFullName: 'openai/o3-mini-2025-01-31',
    provider: ModelProvider.OPENAI,
    maxOutputTokens: 100000,
    contextWindow: 200000,
    inputPrice: 1.1,
    outputPrice: 4.4,
    capabilities: {
      ...OPENAI_REASONING_DEFAULT_CAPABILITIES,
      supportsNativeMCPServer: true,
      supportsNativeCodeExecution: true,
      supportsVision: false,
    },
    openRouterOnly: false,
    deprecated: true,
    description: 'o3-mini reasoning model. Affordable reasoning for STEM tasks. Text-only, 200K context.',
  },
  o1pro: {
    name: 'o1pro',
    fullName: 'o1-pro-2025-03-19',
    shortName: 'o1-pro',
    openrouterFullName: 'openai/o1-pro-2025-03-19',
    provider: ModelProvider.OPENAI,
    maxOutputTokens: 100000,
    contextWindow: 200000,
    inputPrice: 150.0,
    outputPrice: 600.0,
    capabilities: {
      ...OPENAI_REASONING_DEFAULT_CAPABILITIES,
      supportsNativeMCPServer: true,
      supportsVision: true,
    },
    openRouterOnly: false,
    deprecated: true,
    description: 'o1-pro premium reasoning. Highest-quality reasoning for critical tasks. Very high cost. 200K context.',
  },
  o1: {
    name: 'o1',
    fullName: 'o1-2024-12-17',
    shortName: 'o1',
    openrouterFullName: 'openai/o1-2024-12-17',
    provider: ModelProvider.OPENAI,
    maxOutputTokens: 100000,
    contextWindow: 200000,
    inputPrice: 15.0,
    outputPrice: 60.0,
    capabilities: {
      ...OPENAI_REASONING_DEFAULT_CAPABILITIES,
      supportsNativeMCPServer: true,
      supportsVision: true,
      supportsNativePdf: true,
    },
    openRouterOnly: false,
    deprecated: true,
    description: 'o1 reasoning model. First-gen deep reasoning for math, science, and complex analysis. 200K context.',
  },
  o1preview: {
    name: 'o1preview',
    fullName: 'o1-preview-2024-09-12',
    shortName: 'o1-preview',
    openrouterFullName: 'openai/o1-preview-2024-09-12',
    provider: ModelProvider.OPENAI,
    maxOutputTokens: 32768,
    contextWindow: 128000,
    inputPrice: 15.0,
    outputPrice: 60.0,
    capabilities: {
      ...OPENAI_REASONING_DEFAULT_CAPABILITIES,
      supportsVision: false,
      supportsSystemPrompt: false,
    },
    openRouterOnly: false,
    deprecated: true,
    description: 'o1 preview. Early reasoning model preview. No vision or system prompt support. 128K context.',
  },
  'o1-': {
    name: 'o1-',
    fullName: 'o1-mini-2024-09-12',
    shortName: 'o1-mini',
    openrouterFullName: 'openai/o1-mini-2024-09-12',
    provider: ModelProvider.OPENAI,
    maxOutputTokens: 65536,
    contextWindow: 128000,
    inputPrice: 1.1,
    outputPrice: 4.4,
    capabilities: {
      ...OPENAI_REASONING_DEFAULT_CAPABILITIES,
      supportsVision: false,
      supportsSystemPrompt: false,
    },
    openRouterOnly: false,
    deprecated: true,
    description: 'o1-mini. Affordable early reasoning model. Text-only, no system prompt. 128K context.',
  },
  gptoss: {
    name: 'gptoss',
    fullName: 'gpt-oss-120b',
    shortName: 'gpt-oss-120b',
    openrouterFullName: 'openai/gpt-oss-120b',
    provider: ModelProvider.OPENAI,
    maxOutputTokens: 33000,
    contextWindow: 131072,
    inputPrice: 0.15,
    outputPrice: 0.6,
    capabilities: {
      ...OPENAI_REASONING_DEFAULT_CAPABILITIES,
      supportsVision: false,
    },
    openRouterOnly: true,
    deprecated: true,
    description: 'GPT-OSS 120B open-source model. OpenRouter-only, affordable reasoning. 128K context.',
  },
  'gptoss-': {
    name: 'gptoss-',
    fullName: 'gpt-oss-20b',
    shortName: 'gpt-oss-20b',
    openrouterFullName: 'openai/gpt-oss-20b',
    provider: ModelProvider.OPENAI,
    maxOutputTokens: 33000,
    contextWindow: 131072,
    inputPrice: 0.05,
    outputPrice: 0.2,
    capabilities: {
      ...OPENAI_REASONING_DEFAULT_CAPABILITIES,
      supportsVision: false,
    },
    openRouterOnly: true,
    deprecated: true,
    description: 'GPT-OSS 20B open-source model. Ultra-low cost, OpenRouter-only. 128K context.',
  },
  gpt5pro: {
    name: 'gpt5pro',
    fullName: 'gpt-5-pro-2025-10-06',
    shortName: 'gpt-5-pro',
    openrouterFullName: 'openai/gpt-5-pro-2025-10-06',
    provider: ModelProvider.OPENAI,
    maxOutputTokens: 272000,
    contextWindow: 400000,
    inputPrice: 15.0,
    outputPrice: 120.0,
    capabilities: {
      ...OPENAI_REASONING_DEFAULT_CAPABILITIES,
      supportsAutoPromptCaching: false,
      supportsNativeMCPServer: true,
      supportsNativeWebSearch: true,
      supportsNativeCodeExecution: true,
      supportsPredictiveOutput: true,
      supportsVision: true,
      supportsNativePdf: true,
    },
    openRouterOnly: false,
    deprecated: true,
    description: 'GPT-5 Pro. Premium reasoning with massive 272K output and 400K context. Deep analysis and research.',
  },
  gpt5: {
    name: 'gpt5',
    fullName: 'gpt-5-2025-08-07',
    shortName: 'gpt-5',
    openrouterFullName: 'openai/gpt-5-2025-08-07',
    provider: ModelProvider.OPENAI,
    maxOutputTokens: 128000,
    contextWindow: 400000,
    inputPrice: 1.25,
    outputPrice: 10.0,
    capabilities: {
      ...OPENAI_REASONING_DEFAULT_CAPABILITIES,
      cacheDiscountFactor: 0.1,
      supportsNativeMCPServer: true,
      supportsNativeWebSearch: true,
      supportsNativeCodeExecution: true,
      supportsPredictiveOutput: true,
      supportsVision: true,
      supportsNativePdf: true,
    },
    openRouterOnly: false,
    deprecated: true,
    description: 'GPT-5 base. Strong reasoning with great cache savings (90%). 400K context with full tool support.',
  },
  gpt51: {
    name: 'gpt51',
    fullName: 'gpt-5.1-2025-11-13',
    shortName: 'gpt-5.1',
    openrouterFullName: 'openai/gpt-5.1-2025-11-13',
    provider: ModelProvider.OPENAI,
    maxOutputTokens: 128000,
    contextWindow: 400000,
    inputPrice: 1.25,
    outputPrice: 10.0,
    capabilities: {
      ...OPENAI_REASONING_DEFAULT_CAPABILITIES,
      cacheDiscountFactor: 0.1,
      reasoningEffort: ReasoningEffort.HIGH,
      supportsNativeMCPServer: true,
      supportsNativeWebSearch: true,
      supportsNativeCodeExecution: true,
      supportsPredictiveOutput: true,
      supportsVision: true,
      supportsNativePdf: true,
    },
    openRouterOnly: false,
    deprecated: true,
    description: 'GPT-5.1 reasoning model. Improved GPT-5 with better instruction following. 400K context.',
  },
  gpt52pro: {
    name: 'gpt52pro',
    fullName: 'gpt-5.2-pro-2025-12-11',
    shortName: 'gpt-5.2-pro',
    openrouterFullName: 'openai/gpt-5.2-pro',
    provider: ModelProvider.OPENAI,
    maxOutputTokens: 128000,
    contextWindow: 400000,
    inputPrice: 21.0,
    outputPrice: 168.0,
    capabilities: {
      ...OPENAI_REASONING_DEFAULT_CAPABILITIES,
      supportsAutoPromptCaching: false,
      supportsNativeMCPServer: true,
      supportsNativeWebSearch: true,
      supportsNativeCodeExecution: true,
      supportsVision: true,
      supportsNativePdf: true,
      reasoningEffort: ReasoningEffort.XHIGH,
    },
    requiresResponsesAPI: true,
    openRouterOnly: false,
    description: 'GPT-5.2 Pro. Premium deep reasoning with extra-high effort. Requires Responses API. 400K context.',
  },
  gpt52: {
    name: 'gpt52',
    fullName: 'gpt-5.2-2025-12-11',
    shortName: 'gpt-5.2',
    openrouterFullName: 'openai/gpt-5.2',
    provider: ModelProvider.OPENAI,
    maxOutputTokens: 128000,
    contextWindow: 400000,
    inputPrice: 1.75,
    outputPrice: 14.0,
    capabilities: {
      ...OPENAI_REASONING_DEFAULT_CAPABILITIES,
      cacheDiscountFactor: 0.1,
      reasoningEffort: ReasoningEffort.XHIGH,
      supportsNativeMCPServer: true,
      supportsNativeWebSearch: true,
      supportsNativeCodeExecution: true,
      supportsVision: true,
      supportsNativePdf: true,
    },
    openRouterOnly: false,
    description: 'GPT-5.2 reasoning model. Extra-high reasoning effort with 90% cache savings. 400K context.',
  },
  gpt52codex: {
    name: 'gpt52codex',
    fullName: 'gpt-5.2-codex',
    shortName: 'gpt-5.2-codex',
    openrouterFullName: 'openai/gpt-5.2-codex',
    provider: ModelProvider.OPENAI,
    maxOutputTokens: 128000,
    contextWindow: 400000,
    inputPrice: 1.75,
    outputPrice: 14.0,
    capabilities: {
      ...OPENAI_REASONING_DEFAULT_CAPABILITIES,
      cacheDiscountFactor: 0.1,
      reasoningEffort: ReasoningEffort.XHIGH,
      supportsNativeMCPServer: true,
      supportsNativeWebSearch: true,
      supportsNativeCodeExecution: true,
      supportsVision: true,
      supportsNativePdf: true,
    },
    openRouterOnly: false,
    deprecated: true,
    description: 'GPT-5.2 Codex. Code-specialized reasoning model optimized for software development. 400K context.',
  },
  gpt53codex: {
    name: 'gpt53codex',
    fullName: 'gpt-5.3-codex',
    shortName: 'gpt-5.3-codex',
    openrouterFullName: 'openai/gpt-5.3-codex',
    provider: ModelProvider.OPENAI,
    maxOutputTokens: 128000,
    contextWindow: 400000,
    inputPrice: 1.75,
    outputPrice: 14.0,
    capabilities: {
      ...OPENAI_REASONING_DEFAULT_CAPABILITIES,
      cacheDiscountFactor: 0.1,
      reasoningEffort: ReasoningEffort.XHIGH,
      supportsNativeMCPServer: true,
      supportsNativeWebSearch: true,
      supportsNativeCodeExecution: true,
      supportsVision: true,
      supportsNativePdf: true,
    },
    openRouterOnly: false,
    description: 'GPT-5.3 Codex. Latest code-specialized reasoning model for advanced software engineering. 400K context.',
  },
  gpt54pro: {
    name: 'gpt54pro',
    fullName: 'gpt-5.4-pro-2026-03-05',
    shortName: 'gpt-5.4-pro',
    openrouterFullName: 'openai/gpt-5.4-pro',
    provider: ModelProvider.OPENAI,
    maxOutputTokens: 128000,
    contextWindow: 1050000,
    inputPrice: 30.0,
    outputPrice: 180.0,
    capabilities: {
      ...OPENAI_REASONING_DEFAULT_CAPABILITIES,
      supportsAutoPromptCaching: false,
      supportsNativeMCPServer: true,
      supportsNativeWebSearch: true,
      supportsVision: true,
      supportsNativePdf: true,
      reasoningEffort: ReasoningEffort.XHIGH,
    },
    requiresResponsesAPI: true,
    openRouterOnly: false,
    description: 'GPT-5.4 Pro. Most capable OpenAI model with 1M+ context. Premium deep reasoning for the hardest problems.',
  },
  gpt54: {
    name: 'gpt54',
    fullName: 'gpt-5.4-2026-03-05',
    shortName: 'gpt-5.4',
    openrouterFullName: 'openai/gpt-5.4',
    provider: ModelProvider.OPENAI,
    maxOutputTokens: 128000,
    contextWindow: 1050000,
    inputPrice: 2.5,
    outputPrice: 15.0,
    capabilities: {
      ...OPENAI_REASONING_DEFAULT_CAPABILITIES,
      cacheDiscountFactor: 0.1,
      reasoningEffort: ReasoningEffort.XHIGH,
      supportsNativeMCPServer: true,
      supportsNativeWebSearch: true,
      supportsNativeCodeExecution: true,
      supportsPredictiveOutput: true,
      supportsVision: true,
      supportsNativePdf: true,
    },
    openRouterOnly: false,
    description: 'GPT-5.4 flagship. Latest OpenAI reasoning model with 1M+ context, extra-high effort, and 90% cache savings.',
  },
  'gpt5-': {
    name: 'gpt5-',
    fullName: 'gpt-5-mini-2025-08-07',
    shortName: 'gpt-5-mini',
    openrouterFullName: 'openai/gpt-5-mini-2025-08-07',
    provider: ModelProvider.OPENAI,
    maxOutputTokens: 128000,
    contextWindow: 400000,
    inputPrice: 0.25,
    outputPrice: 2.0,
    capabilities: {
      ...OPENAI_REASONING_DEFAULT_CAPABILITIES,
      cacheDiscountFactor: 0.1,
      supportsNativeMCPServer: true,
      supportsNativeWebSearch: true,
      supportsNativeCodeExecution: true,
      supportsPredictiveOutput: true,
      supportsVision: true,
      supportsNativePdf: true,
    },
    openRouterOnly: false,
    deprecated: true,
    description: 'GPT-5 mini. Affordable reasoning model for cost-sensitive workflows. 400K context.',
  },
  'gpt5--': {
    name: 'gpt5--',
    fullName: 'gpt-5-nano-2025-08-07',
    shortName: 'gpt-5-nano',
    openrouterFullName: 'openai/gpt-5-nano-2025-08-07',
    provider: ModelProvider.OPENAI,
    maxOutputTokens: 128000,
    contextWindow: 400000,
    inputPrice: 0.05,
    outputPrice: 0.4,
    capabilities: {
      ...OPENAI_REASONING_DEFAULT_CAPABILITIES,
      cacheDiscountFactor: 0.1,
      supportsNativeMCPServer: true,
      supportsNativeWebSearch: true,
      supportsNativeCodeExecution: true,
      supportsPredictiveOutput: true,
      supportsVision: true,
      supportsNativePdf: true,
    },
    openRouterOnly: false,
    deprecated: true,
    description: 'GPT-5 nano. Ultra-low cost reasoning for simple tasks and high-volume processing. 400K context.',
  },
};
