import {
  DEFAULT_MODEL_CAPABILITIES,
  ModelCapabilities,
  ModelEntry,
  ModelProvider,
} from '../ModelConfig';

/**
 * Default capabilities for OpenAI GPT models.
 * OpenAI models feature automatic prompt caching with 50% cost savings.
 */
const OPENAI_DEFAULT_CAPABILITIES: ModelCapabilities = {
  ...DEFAULT_MODEL_CAPABILITIES,
  supportsAutoPromptCaching: true,
  cacheDiscountFactor: 0.5,
  supportsIntermDevMsgs: true,
  supportsVision: true,
  supportsNativePdf: true,
  supportsNativeMCPServer: false,
  supportsNativeWebSearch: false,
  supportsNativeCodeExecution: false,
};

/**
 * OpenAI GPT model configurations.
 * Includes GPT-4.x, GPT-4o, GPT-4.5, and Chat Latest variants.
 */
export const OPENAI_MODELS: readonly ModelEntry[] = [
  {
    label: 'GPT-4.1',
    id: 'gpt-4.1-2025-04-14',
    shortName: 'gpt-4.1',
    openrouterFullName: 'openai/gpt-4.1',
    vscodeLMFullName: 'gpt-4.1',
    provider: ModelProvider.OPENAI,
    maxOutputTokens: 32768,
    contextWindow: 1000000,
    inputPrice: 2.0,
    outputPrice: 8.0,
    capabilities: {
      ...OPENAI_DEFAULT_CAPABILITIES,
      cacheDiscountFactor: 0.25,
      supportsNativeMCPServer: true,
      supportsNativeWebSearch: true,
      supportsNativeCodeExecution: true,
      supportsPredictiveOutput: true,
    },
    tiers: { fast: { inputPrice: 3.5, outputPrice: 14 } },
    source: { url: 'https://developers.openai.com/api/docs/models/gpt-4.1', verified: '2026-09-30' },
    legacyKeys: { gpt41: {} },
    openRouterOnly: false,
    deprecated: true,
  },
  {
    label: 'GPT-4.1 Mini',
    id: 'gpt-4.1-mini-2025-04-14',
    shortName: 'gpt-4.1-mini',
    openrouterFullName: 'openai/gpt-4.1-mini',
    vscodeLMFullName: 'gpt-4.1-mini',
    provider: ModelProvider.OPENAI,
    maxOutputTokens: 32768,
    contextWindow: 1000000,
    inputPrice: 0.4,
    outputPrice: 1.6,
    capabilities: {
      ...OPENAI_DEFAULT_CAPABILITIES,
      cacheDiscountFactor: 0.25,
      supportsNativeMCPServer: true,
      supportsNativeWebSearch: true,
      supportsNativeCodeExecution: true,
      supportsPredictiveOutput: true,
    },
    tiers: { fast: { inputPrice: 0.7, outputPrice: 2.8 } },
    source: { url: 'https://developers.openai.com/api/docs/models/gpt-4.1-mini', verified: '2026-09-30' },
    legacyKeys: { 'gpt41-': {} },
    openRouterOnly: false,
    deprecated: true,
  },
  {
    label: 'GPT-4.1 Nano',
    id: 'gpt-4.1-nano-2025-04-14',
    shortName: 'gpt-4.1-nano',
    openrouterFullName: 'openai/gpt-4.1-nano',
    provider: ModelProvider.OPENAI,
    maxOutputTokens: 32768,
    contextWindow: 1000000,
    inputPrice: 0.1,
    outputPrice: 0.4,
    capabilities: {
      ...OPENAI_DEFAULT_CAPABILITIES,
      cacheDiscountFactor: 0.25,
      supportsNativeMCPServer: true,
      supportsNativeWebSearch: true,
      supportsNativeCodeExecution: true,
      supportsPredictiveOutput: true,
    },
    tiers: { fast: { inputPrice: 0.2, outputPrice: 0.8 } },
    source: { url: 'https://developers.openai.com/api/docs/models/gpt-4.1-nano', verified: '2026-09-30' },
    legacyKeys: { 'gpt41--': {} },
    openRouterOnly: false,
    deprecated: true,
  },
  {
    label: 'GPT-4.5 Preview',
    id: 'gpt-4.5-preview',
    shortName: 'gpt-4.5-preview',
    openrouterFullName: 'openai/gpt-4.5-preview',
    provider: ModelProvider.OPENAI,
    maxOutputTokens: 16384,
    contextWindow: 128000,
    inputPrice: 75.0,
    outputPrice: 150.0,
    capabilities: {
      ...OPENAI_DEFAULT_CAPABILITIES,
      supportsPredictiveOutput: false,
    },
    legacyKeys: { gpt45: {} },
    openRouterOnly: false,
    deprecated: true,
    retired: true,
  },
  {
    label: 'GPT-4o',
    id: 'gpt-4o-2024-11-20',
    shortName: 'gpt-4o',
    openrouterFullName: 'openai/gpt-4o-2024-11-20',
    vscodeLMFullName: 'gpt-4o',
    provider: ModelProvider.OPENAI,
    maxOutputTokens: 16384,
    contextWindow: 128000,
    inputPrice: 2.5,
    outputPrice: 10.0,
    capabilities: {
      ...OPENAI_DEFAULT_CAPABILITIES,
      supportsNativeMCPServer: true,
      supportsNativeWebSearch: true,
      supportsNativeCodeExecution: true,
      supportsPredictiveOutput: true,
    },
    tiers: { fast: { inputPrice: 4.25, outputPrice: 17 } },
    source: { url: 'https://developers.openai.com/api/docs/models/gpt-4o', verified: '2026-09-30' },
    legacyKeys: { gpt4o: {} },
    openRouterOnly: false,
    deprecated: true,
  },
  {
    label: 'GPT-4 Turbo',
    id: 'gpt-4-turbo-2024-04-09',
    shortName: 'gpt-4-turbo',
    openrouterFullName: 'openai/gpt-4-turbo-2024-04-09',
    provider: ModelProvider.OPENAI,
    maxOutputTokens: 4096,
    contextWindow: 128000,
    inputPrice: 10.0,
    outputPrice: 30.0,
    capabilities: {
      ...OPENAI_DEFAULT_CAPABILITIES,
      supportsAutoPromptCaching: false,
    },
    source: { url: 'https://developers.openai.com/api/docs/deprecations', verified: '2026-09-30' },
    legacyKeys: { gpt4t: {} },
    openRouterOnly: false,
    // Deprecated; OpenAI shuts it down on 2026-10-23.
    deprecated: true,
  },
  {
    label: 'GPT-4o Mini',
    id: 'gpt-4o-mini-2024-07-18',
    shortName: 'gpt-4o-mini',
    openrouterFullName: 'openai/gpt-4o-mini-2024-07-18',
    vscodeLMFullName: 'gpt-4o-mini',
    provider: ModelProvider.OPENAI,
    maxOutputTokens: 16384,
    contextWindow: 128000,
    inputPrice: 0.15,
    outputPrice: 0.6,
    capabilities: {
      ...OPENAI_DEFAULT_CAPABILITIES,
      supportsPredictiveOutput: true,
    },
    tiers: { fast: { inputPrice: 0.25, outputPrice: 1 } },
    source: { url: 'https://developers.openai.com/api/docs/models/gpt-4o-mini', verified: '2026-09-30' },
    legacyKeys: { 'gpt4o-': {} },
    openRouterOnly: false,
    deprecated: true,
  },
  // Chat Latest (`chat-latest`): moving alias for the latest Instant model
  // used in ChatGPT; OpenAI recommends GPT-6 Astra for production API use.
  // $5 / $30, cached input $0.50 (0.1x); no Fast-tier price. Text + image
  // input; no reasoning token support listed. Responses tools: web search,
  // file search, code interpreter, MCP.
  {
    label: 'Chat Latest',
    id: 'chat-latest',
    shortName: 'chat-latest',
    openrouterFullName: 'openai/gpt-chat-latest',
    provider: ModelProvider.OPENAI,
    maxOutputTokens: 128000,
    contextWindow: 400000,
    inputPrice: 5.0,
    outputPrice: 30.0,
    capabilities: {
      ...OPENAI_DEFAULT_CAPABILITIES,
      cacheDiscountFactor: 0.1,
      supportsNativeMCPServer: true,
      supportsNativeWebSearch: true,
      supportsNativeCodeExecution: true,
    },
    source: { url: 'https://developers.openai.com/api/docs/models/chat-latest', verified: '2026-09-30' },
    legacyKeys: { chatlatest: {} },
    openRouterOnly: false,
  },
  {
    label: 'ChatGPT-4o Latest',
    id: 'chatgpt-4o-latest',
    shortName: 'chatgpt-4o-latest',
    openrouterFullName: 'openai/chatgpt-4o-latest',
    provider: ModelProvider.OPENAI,
    maxOutputTokens: 16384,
    contextWindow: 128000,
    inputPrice: 5.0,
    outputPrice: 15.0,
    capabilities: {
      ...OPENAI_DEFAULT_CAPABILITIES,
    },
    reasoning: { efforts: [] },
    legacyKeys: { gpt4ol: {} },
    openRouterOnly: false,
    deprecated: true,
    retired: true,
  },
];
