import {
  DEFAULT_MODEL_CAPABILITIES,
  ModelCapabilities,
  ModelConfig,
  ModelProvider,
  ReasoningEffort,
} from '../ModelConfig';

/**
 * Default capabilities for OpenAI reasoning models (o-series).
 * These models feature extended reasoning with configurable effort levels.
 */
const OPENAI_REASONING_DEFAULT_CAPABILITIES: ModelCapabilities = {
  ...DEFAULT_MODEL_CAPABILITIES,
  supportsAutoPromptCaching: true,
  cacheDiscountFactor: 0.5,
  supportsReasoning: true,
  supportsIntermDevMsgs: true,
  reasoningEffort: ReasoningEffort.HIGH,
  supportsReasoningEffort: true,
};

/**
 * OpenAI reasoning model configurations.
 * Includes o1, o3, o4, and GPT-5 reasoning variants.
 */
export const OPENAI_REASONING_MODELS: Record<string, ModelConfig> = {
  'o4-': {
    name: 'o4-',
    fullName: 'o4-mini-2025-04-16',
    openrouterFullName: 'openai/o4-mini-high',
    provider: ModelProvider.OPENAI,
    maxOutputTokens: 100000,
    contextWindow: 200000,
    inputPrice: 1.0,
    outputPrice: 4.4,
    capabilities: {
      ...OPENAI_REASONING_DEFAULT_CAPABILITIES,
      cacheDiscountFactor: 0.25,
      supportsNativeWebSearch: true,
      supportsNativeMCPServer: true,
      supportsNativeCodeExecution: true,
      supportsNativePdf: true,
      supportsVision: true,
    },
    openRouterOnly: false,
  },
  o3pro: {
    name: 'o3pro',
    fullName: 'o3-pro-2025-06-10',
    openrouterFullName: 'openai/o3-pro',
    provider: ModelProvider.OPENAI,
    maxOutputTokens: 100000,
    contextWindow: 200000,
    inputPrice: 20.0,
    outputPrice: 80.0,
    capabilities: {
      ...OPENAI_REASONING_DEFAULT_CAPABILITIES,
      supportsNativeWebSearch: true,
      supportsNativeMCPServer: true,
      supportsAutoPromptCaching: false,
      supportsNativePdf: true,
      supportsVision: true,
    },
    openRouterOnly: false,
  },
  o3: {
    name: 'o3',
    fullName: 'o3-2025-04-16',
    openrouterFullName: 'openai/o3',
    provider: ModelProvider.OPENAI,
    maxOutputTokens: 100000,
    contextWindow: 200000,
    inputPrice: 2.0,
    outputPrice: 8.0,
    capabilities: {
      ...OPENAI_REASONING_DEFAULT_CAPABILITIES,
      cacheDiscountFactor: 0.25,
      supportsNativeWebSearch: true,
      supportsNativeMCPServer: true,
      supportsNativeCodeExecution: true,
      supportsNativePdf: true,
      supportsVision: true,
    },
    openRouterOnly: false,
  },
  'o3-': {
    name: 'o3-',
    fullName: 'o3-mini-2025-01-31',
    openrouterFullName: 'openai/o3-mini-2025-01-31',
    provider: ModelProvider.OPENAI,
    maxOutputTokens: 100000,
    contextWindow: 200000,
    inputPrice: 1.1,
    outputPrice: 4.4,
    capabilities: {
      ...OPENAI_REASONING_DEFAULT_CAPABILITIES,
      supportsNativeMCPServer: true,
      supportsNativeCodeExecution: true,
      supportsVision: false,
    },
    openRouterOnly: false,
  },
  o1pro: {
    name: 'o1pro',
    fullName: 'o1-pro-2025-03-19',
    openrouterFullName: 'openai/o1-pro-2025-03-19',
    provider: ModelProvider.OPENAI,
    maxOutputTokens: 100000,
    contextWindow: 200000,
    inputPrice: 150.0,
    outputPrice: 600.0,
    capabilities: {
      ...OPENAI_REASONING_DEFAULT_CAPABILITIES,
      supportsNativeMCPServer: true,
      supportsVision: true,
    },
    openRouterOnly: false,
  },
  o1: {
    name: 'o1',
    fullName: 'o1-2024-12-17',
    openrouterFullName: 'openai/o1-2024-12-17',
    provider: ModelProvider.OPENAI,
    maxOutputTokens: 100000,
    contextWindow: 200000,
    inputPrice: 15.0,
    outputPrice: 60.0,
    capabilities: {
      ...OPENAI_REASONING_DEFAULT_CAPABILITIES,
      supportsNativeMCPServer: true,
      supportsVision: true,
      supportsNativePdf: true,
    },
    openRouterOnly: false,
  },
  o1preview: {
    name: 'o1preview',
    fullName: 'o1-preview-2024-09-12',
    openrouterFullName: 'openai/o1-preview-2024-09-12',
    provider: ModelProvider.OPENAI,
    maxOutputTokens: 32768,
    contextWindow: 128000,
    inputPrice: 15.0,
    outputPrice: 60.0,
    capabilities: {
      ...OPENAI_REASONING_DEFAULT_CAPABILITIES,
      supportsVision: false,
      supportsSystemPrompt: false,
    },
    openRouterOnly: false,
  },
  'o1-': {
    name: 'o1-',
    fullName: 'o1-mini-2024-09-12',
    openrouterFullName: 'openai/o1-mini-2024-09-12',
    provider: ModelProvider.OPENAI,
    maxOutputTokens: 65536,
    contextWindow: 128000,
    inputPrice: 1.1,
    outputPrice: 4.4,
    capabilities: {
      ...OPENAI_REASONING_DEFAULT_CAPABILITIES,
      supportsVision: false,
      supportsSystemPrompt: false,
    },
    openRouterOnly: false,
  },
  gptoss: {
    name: 'gptoss',
    fullName: 'gpt-oss-120b',
    openrouterFullName: 'openai/gpt-oss-120b',
    provider: ModelProvider.OPENAI,
    maxOutputTokens: 33000,
    contextWindow: 131072,
    inputPrice: 0.15,
    outputPrice: 0.6,
    capabilities: {
      ...OPENAI_REASONING_DEFAULT_CAPABILITIES,
      supportsVision: false,
    },
    openRouterOnly: true,
  },
  'gptoss-': {
    name: 'gptoss-',
    fullName: 'gpt-oss-20b',
    openrouterFullName: 'openai/gpt-oss-20b',
    provider: ModelProvider.OPENAI,
    maxOutputTokens: 33000,
    contextWindow: 131072,
    inputPrice: 0.05,
    outputPrice: 0.2,
    capabilities: {
      ...OPENAI_REASONING_DEFAULT_CAPABILITIES,
      supportsVision: false,
    },
    openRouterOnly: true,
  },
  gpt5pro: {
    name: 'gpt5pro',
    fullName: 'gpt-5-pro-2025-10-06',
    openrouterFullName: 'openai/gpt-5-pro-2025-10-06',
    provider: ModelProvider.OPENAI,
    maxOutputTokens: 272000,
    contextWindow: 400000,
    inputPrice: 15.0,
    outputPrice: 120.0,
    capabilities: {
      ...OPENAI_REASONING_DEFAULT_CAPABILITIES,
      supportsAutoPromptCaching: false,
      supportsNativeMCPServer: true,
      supportsNativeWebSearch: true,
      supportsNativeCodeExecution: true,
      supportsPredictiveOutput: true,
      supportsVision: true,
      supportsNativePdf: true,
    },
    openRouterOnly: false,
  },
  gpt5: {
    name: 'gpt5',
    fullName: 'gpt-5-2025-08-07',
    openrouterFullName: 'openai/gpt-5-2025-08-07',
    provider: ModelProvider.OPENAI,
    maxOutputTokens: 128000,
    contextWindow: 400000,
    inputPrice: 1.25,
    outputPrice: 10.0,
    capabilities: {
      ...OPENAI_REASONING_DEFAULT_CAPABILITIES,
      cacheDiscountFactor: 0.1,
      supportsNativeMCPServer: true,
      supportsNativeWebSearch: true,
      supportsNativeCodeExecution: true,
      supportsPredictiveOutput: true,
      supportsVision: true,
      supportsNativePdf: true,
    },
    openRouterOnly: false,
  },
  gpt51: {
    name: 'gpt51',
    fullName: 'gpt-5.1-2025-11-13',
    openrouterFullName: 'openai/gpt-5.1-2025-11-13',
    provider: ModelProvider.OPENAI,
    maxOutputTokens: 128000,
    contextWindow: 400000,
    inputPrice: 1.25,
    outputPrice: 10.0,
    capabilities: {
      ...OPENAI_REASONING_DEFAULT_CAPABILITIES,
      cacheDiscountFactor: 0.1,
      reasoningEffort: ReasoningEffort.HIGH,
      supportsNativeMCPServer: true,
      supportsNativeWebSearch: true,
      supportsNativeCodeExecution: true,
      supportsPredictiveOutput: true,
      supportsVision: true,
      supportsNativePdf: true,
    },
    openRouterOnly: false,
  },
  gpt52pro: {
    name: 'gpt52pro',
    fullName: 'gpt-5.2-pro-2025-12-11',
    openrouterFullName: 'openai/gpt-5.2-pro',
    provider: ModelProvider.OPENAI,
    maxOutputTokens: 128000,
    contextWindow: 400000,
    inputPrice: 21.0,
    outputPrice: 168.0,
    capabilities: {
      ...OPENAI_REASONING_DEFAULT_CAPABILITIES,
      supportsAutoPromptCaching: false,
      supportsNativeMCPServer: true,
      supportsNativeWebSearch: true,
      supportsNativeCodeExecution: true,
      supportsVision: true,
      supportsNativePdf: true,
      reasoningEffort: ReasoningEffort.XHIGH,
    },
    requiresResponsesAPI: true,
    openRouterOnly: false,
  },
  gpt52: {
    name: 'gpt52',
    fullName: 'gpt-5.2-2025-12-11',
    openrouterFullName: 'openai/gpt-5.2',
    provider: ModelProvider.OPENAI,
    maxOutputTokens: 128000,
    contextWindow: 400000,
    inputPrice: 1.75,
    outputPrice: 14.0,
    capabilities: {
      ...OPENAI_REASONING_DEFAULT_CAPABILITIES,
      cacheDiscountFactor: 0.1,
      reasoningEffort: ReasoningEffort.XHIGH,
      supportsNativeMCPServer: true,
      supportsNativeWebSearch: true,
      supportsNativeCodeExecution: true,
      supportsVision: true,
      supportsNativePdf: true,
    },
    openRouterOnly: false,
  },
  'gpt5-': {
    name: 'gpt5-',
    fullName: 'gpt-5-mini-2025-08-07',
    openrouterFullName: 'openai/gpt-5-mini-2025-08-07',
    provider: ModelProvider.OPENAI,
    maxOutputTokens: 128000,
    contextWindow: 400000,
    inputPrice: 0.25,
    outputPrice: 2.0,
    capabilities: {
      ...OPENAI_REASONING_DEFAULT_CAPABILITIES,
      cacheDiscountFactor: 0.1,
      supportsNativeMCPServer: true,
      supportsNativeWebSearch: true,
      supportsNativeCodeExecution: true,
      supportsPredictiveOutput: true,
      supportsVision: true,
      supportsNativePdf: true,
    },
    openRouterOnly: false,
  },
  'gpt5--': {
    name: 'gpt5--',
    fullName: 'gpt-5-nano-2025-08-07',
    openrouterFullName: 'openai/gpt-5-nano-2025-08-07',
    provider: ModelProvider.OPENAI,
    maxOutputTokens: 128000,
    contextWindow: 400000,
    inputPrice: 0.05,
    outputPrice: 0.4,
    capabilities: {
      ...OPENAI_REASONING_DEFAULT_CAPABILITIES,
      cacheDiscountFactor: 0.1,
      supportsNativeMCPServer: true,
      supportsNativeWebSearch: true,
      supportsNativeCodeExecution: true,
      supportsPredictiveOutput: true,
      supportsVision: true,
      supportsNativePdf: true,
    },
    openRouterOnly: false,
  },
};
