import {
  DEFAULT_MODEL_CAPABILITIES,
  ModelCapabilities,
  ModelConfig,
  ModelProvider,
  ReasoningEffort,
} from '../ModelConfig';

/**
 * Default capabilities for OpenAI reasoning models (o-series).
 * These models feature extended reasoning with configurable effort levels.
 */
const OPENAI_REASONING_DEFAULT_CAPABILITIES: ModelCapabilities = {
  ...DEFAULT_MODEL_CAPABILITIES,
  supportsAutoPromptCaching: true,
  cacheDiscountFactor: 0.5,
  supportsReasoning: true,
  supportsIntermDevMsgs: true,
  reasoningEffort: ReasoningEffort.HIGH,
  supportsReasoningEffort: true,
};

/**
 * OpenAI reasoning model configurations.
 * Includes o1, o3, o4, and GPT-5 reasoning variants.
 */
export const OPENAI_REASONING_MODELS: Record<string, ModelConfig> = {
  'o4-': {
    name: 'o4-',
    label: 'o4 Mini',
    fullName: 'o4-mini-2025-04-16',
    shortName: 'o4-mini',
    openrouterFullName: 'openai/o4-mini-high',
    vscodeLMFullName: 'o4-mini',
    provider: ModelProvider.OPENAI,
    maxOutputTokens: 100000,
    contextWindow: 200000,
    inputPrice: 1.1,
    outputPrice: 4.4,
    capabilities: {
      ...OPENAI_REASONING_DEFAULT_CAPABILITIES,
      cacheDiscountFactor: 0.25,
      supportsNativeWebSearch: true,
      supportsNativeMCPServer: true,
      supportsNativeCodeExecution: true,
      supportsNativePdf: true,
      supportsVision: true,
    },
    openRouterOnly: false,
    deprecated: true,
  },
  o3pro: {
    name: 'o3pro',
    label: 'o3 Pro',
    fullName: 'o3-pro-2025-06-10',
    shortName: 'o3-pro',
    openrouterFullName: 'openai/o3-pro',
    vscodeLMFullName: 'o3-pro',
    provider: ModelProvider.OPENAI,
    maxOutputTokens: 100000,
    contextWindow: 200000,
    inputPrice: 20.0,
    outputPrice: 80.0,
    capabilities: {
      ...OPENAI_REASONING_DEFAULT_CAPABILITIES,
      supportsNativeWebSearch: true,
      supportsNativeMCPServer: true,
      supportsAutoPromptCaching: false,
      supportsNativePdf: true,
      supportsVision: true,
    },
    openRouterOnly: false,
    deprecated: true,
  },
  o3: {
    name: 'o3',
    label: 'o3',
    fullName: 'o3-2025-04-16',
    shortName: 'o3',
    openrouterFullName: 'openai/o3',
    vscodeLMFullName: 'o3',
    provider: ModelProvider.OPENAI,
    maxOutputTokens: 100000,
    contextWindow: 200000,
    inputPrice: 2.0,
    outputPrice: 8.0,
    capabilities: {
      ...OPENAI_REASONING_DEFAULT_CAPABILITIES,
      cacheDiscountFactor: 0.25,
      supportsNativeWebSearch: true,
      supportsNativeMCPServer: true,
      supportsNativeCodeExecution: true,
      supportsNativePdf: true,
      supportsVision: true,
    },
    openRouterOnly: false,
    deprecated: true,
  },
  'o3-': {
    name: 'o3-',
    label: 'o3 Mini',
    fullName: 'o3-mini-2025-01-31',
    shortName: 'o3-mini',
    openrouterFullName: 'openai/o3-mini-2025-01-31',
    vscodeLMFullName: 'o3-mini',
    provider: ModelProvider.OPENAI,
    maxOutputTokens: 100000,
    contextWindow: 200000,
    inputPrice: 1.1,
    outputPrice: 4.4,
    capabilities: {
      ...OPENAI_REASONING_DEFAULT_CAPABILITIES,
      supportsNativeMCPServer: true,
      supportsNativeCodeExecution: true,
      supportsVision: false,
    },
    openRouterOnly: false,
    deprecated: true,
  },
  o1pro: {
    name: 'o1pro',
    label: 'o1 Pro',
    fullName: 'o1-pro-2025-03-19',
    shortName: 'o1-pro',
    openrouterFullName: 'openai/o1-pro-2025-03-19',
    provider: ModelProvider.OPENAI,
    maxOutputTokens: 100000,
    contextWindow: 200000,
    inputPrice: 150.0,
    outputPrice: 600.0,
    capabilities: {
      ...OPENAI_REASONING_DEFAULT_CAPABILITIES,
      supportsNativeMCPServer: true,
      supportsVision: true,
    },
    openRouterOnly: false,
    deprecated: true,
  },
  o1: {
    name: 'o1',
    label: 'o1',
    fullName: 'o1-2024-12-17',
    shortName: 'o1',
    openrouterFullName: 'openai/o1-2024-12-17',
    vscodeLMFullName: 'o1',
    provider: ModelProvider.OPENAI,
    maxOutputTokens: 100000,
    contextWindow: 200000,
    inputPrice: 15.0,
    outputPrice: 60.0,
    capabilities: {
      ...OPENAI_REASONING_DEFAULT_CAPABILITIES,
      supportsNativeMCPServer: true,
      supportsVision: true,
      supportsNativePdf: true,
    },
    openRouterOnly: false,
    deprecated: true,
  },
  o1preview: {
    name: 'o1preview',
    label: 'o1 Preview',
    fullName: 'o1-preview-2024-09-12',
    shortName: 'o1-preview',
    openrouterFullName: 'openai/o1-preview-2024-09-12',
    vscodeLMFullName: 'o1-preview',
    provider: ModelProvider.OPENAI,
    maxOutputTokens: 32768,
    contextWindow: 128000,
    inputPrice: 15.0,
    outputPrice: 60.0,
    capabilities: {
      ...OPENAI_REASONING_DEFAULT_CAPABILITIES,
      supportsVision: false,
      supportsSystemPrompt: false,
    },
    openRouterOnly: false,
    deprecated: true,
    retired: true,
  },
  'o1-': {
    name: 'o1-',
    label: 'o1 Mini',
    fullName: 'o1-mini-2024-09-12',
    shortName: 'o1-mini',
    openrouterFullName: 'openai/o1-mini-2024-09-12',
    vscodeLMFullName: 'o1-mini',
    provider: ModelProvider.OPENAI,
    maxOutputTokens: 65536,
    contextWindow: 128000,
    inputPrice: 1.1,
    outputPrice: 4.4,
    capabilities: {
      ...OPENAI_REASONING_DEFAULT_CAPABILITIES,
      supportsVision: false,
      supportsSystemPrompt: false,
    },
    openRouterOnly: false,
    deprecated: true,
    retired: true,
  },
  gptoss: {
    name: 'gptoss',
    label: 'GPT-OSS 120B',
    fullName: 'gpt-oss-120b',
    shortName: 'gpt-oss-120b',
    openrouterFullName: 'openai/gpt-oss-120b',
    provider: ModelProvider.OPENAI,
    maxOutputTokens: 33000,
    contextWindow: 131072,
    inputPrice: 0.15,
    outputPrice: 0.6,
    capabilities: {
      ...OPENAI_REASONING_DEFAULT_CAPABILITIES,
      supportsVision: false,
    },
    openRouterOnly: true,
    deprecated: true,
  },
  'gptoss-': {
    name: 'gptoss-',
    label: 'GPT-OSS 20B',
    fullName: 'gpt-oss-20b',
    shortName: 'gpt-oss-20b',
    openrouterFullName: 'openai/gpt-oss-20b',
    provider: ModelProvider.OPENAI,
    maxOutputTokens: 33000,
    contextWindow: 131072,
    inputPrice: 0.05,
    outputPrice: 0.2,
    capabilities: {
      ...OPENAI_REASONING_DEFAULT_CAPABILITIES,
      supportsVision: false,
    },
    openRouterOnly: true,
    deprecated: true,
  },
  gpt5pro: {
    name: 'gpt5pro',
    label: 'GPT-5 Pro',
    fullName: 'gpt-5-pro-2025-10-06',
    shortName: 'gpt-5-pro',
    openrouterFullName: 'openai/gpt-5-pro-2025-10-06',
    vscodeLMFullName: 'gpt-5-pro',
    provider: ModelProvider.OPENAI,
    maxOutputTokens: 272000,
    contextWindow: 400000,
    inputPrice: 15.0,
    outputPrice: 120.0,
    capabilities: {
      ...OPENAI_REASONING_DEFAULT_CAPABILITIES,
      supportsAutoPromptCaching: false,
      supportsNativeMCPServer: true,
      supportsNativeWebSearch: true,
      supportsNativeCodeExecution: true,
      supportsPredictiveOutput: true,
      supportsVision: true,
      supportsNativePdf: true,
    },
    openRouterOnly: false,
    deprecated: true,
  },
  gpt5: {
    name: 'gpt5',
    label: 'GPT-5',
    fullName: 'gpt-5-2025-08-07',
    shortName: 'gpt-5',
    openrouterFullName: 'openai/gpt-5-2025-08-07',
    vscodeLMFullName: 'gpt-5',
    provider: ModelProvider.OPENAI,
    maxOutputTokens: 128000,
    contextWindow: 400000,
    inputPrice: 1.25,
    outputPrice: 10.0,
    capabilities: {
      ...OPENAI_REASONING_DEFAULT_CAPABILITIES,
      cacheDiscountFactor: 0.1,
      supportsNativeMCPServer: true,
      supportsNativeWebSearch: true,
      supportsNativeCodeExecution: true,
      supportsPredictiveOutput: true,
      supportsVision: true,
      supportsNativePdf: true,
    },
    openRouterOnly: false,
    deprecated: true,
  },
  gpt51: {
    name: 'gpt51',
    label: 'GPT-5.1',
    fullName: 'gpt-5.1-2025-11-13',
    shortName: 'gpt-5.1',
    openrouterFullName: 'openai/gpt-5.1-2025-11-13',
    vscodeLMFullName: 'gpt-5.1',
    provider: ModelProvider.OPENAI,
    maxOutputTokens: 128000,
    contextWindow: 400000,
    inputPrice: 1.25,
    outputPrice: 10.0,
    capabilities: {
      ...OPENAI_REASONING_DEFAULT_CAPABILITIES,
      cacheDiscountFactor: 0.1,
      reasoningEffort: ReasoningEffort.HIGH,
      supportsNativeMCPServer: true,
      supportsNativeWebSearch: true,
      supportsNativeCodeExecution: true,
      supportsPredictiveOutput: true,
      supportsVision: true,
      supportsNativePdf: true,
    },
    openRouterOnly: false,
    deprecated: true,
  },
  gpt52pro: {
    name: 'gpt52pro',
    label: 'GPT-5.2 Pro',
    fullName: 'gpt-5.2-pro-2025-12-11',
    shortName: 'gpt-5.2-pro',
    openrouterFullName: 'openai/gpt-5.2-pro',
    vscodeLMFullName: 'gpt-5.2-pro',
    provider: ModelProvider.OPENAI,
    maxOutputTokens: 128000,
    contextWindow: 400000,
    inputPrice: 21.0,
    outputPrice: 168.0,
    capabilities: {
      ...OPENAI_REASONING_DEFAULT_CAPABILITIES,
      supportsAutoPromptCaching: false,
      supportsNativeMCPServer: true,
      supportsNativeWebSearch: true,
      supportsNativeCodeExecution: true,
      supportsVision: true,
      supportsNativePdf: true,
      reasoningEffort: ReasoningEffort.XHIGH,
    },
    requiresResponsesAPI: true,
    openRouterOnly: false,
    deprecated: true,
  },
  gpt52: {
    name: 'gpt52',
    label: 'GPT-5.2',
    fullName: 'gpt-5.2-2025-12-11',
    shortName: 'gpt-5.2',
    openrouterFullName: 'openai/gpt-5.2',
    vscodeLMFullName: 'gpt-5.2',
    provider: ModelProvider.OPENAI,
    maxOutputTokens: 128000,
    contextWindow: 400000,
    inputPrice: 1.75,
    outputPrice: 14.0,
    capabilities: {
      ...OPENAI_REASONING_DEFAULT_CAPABILITIES,
      cacheDiscountFactor: 0.1,
      reasoningEffort: ReasoningEffort.XHIGH,
      supportsNativeMCPServer: true,
      supportsNativeWebSearch: true,
      supportsNativeCodeExecution: true,
      supportsVision: true,
      supportsNativePdf: true,
    },
    openRouterOnly: false,
    deprecated: true,
  },
  gpt52codex: {
    name: 'gpt52codex',
    label: 'GPT-5.2 Codex',
    fullName: 'gpt-5.2-codex',
    shortName: 'gpt-5.2-codex',
    openrouterFullName: 'openai/gpt-5.2-codex',
    vscodeLMFullName: 'gpt-5.2-codex',
    provider: ModelProvider.OPENAI,
    maxOutputTokens: 128000,
    contextWindow: 400000,
    inputPrice: 1.75,
    outputPrice: 14.0,
    capabilities: {
      ...OPENAI_REASONING_DEFAULT_CAPABILITIES,
      cacheDiscountFactor: 0.1,
      reasoningEffort: ReasoningEffort.XHIGH,
      supportsNativeMCPServer: true,
      supportsNativeWebSearch: true,
      supportsNativeCodeExecution: true,
      supportsVision: true,
      supportsNativePdf: true,
    },
    openRouterOnly: false,
    deprecated: true,
    retired: true,
  },
  gpt53codex: {
    name: 'gpt53codex',
    label: 'GPT-5.3 Codex',
    fullName: 'gpt-5.3-codex',
    shortName: 'gpt-5.3-codex',
    openrouterFullName: 'openai/gpt-5.3-codex',
    vscodeLMFullName: 'gpt-5.3-codex',
    copilotFullName: 'gpt-5.3-codex',
    provider: ModelProvider.OPENAI,
    maxOutputTokens: 128000,
    contextWindow: 400000,
    inputPrice: 1.75,
    outputPrice: 14.0,
    capabilities: {
      ...OPENAI_REASONING_DEFAULT_CAPABILITIES,
      cacheDiscountFactor: 0.1,
      reasoningEffort: ReasoningEffort.XHIGH,
      supportsNativeMCPServer: true,
      supportsNativeWebSearch: true,
      supportsNativeCodeExecution: true,
      supportsVision: true,
      supportsNativePdf: true,
    },
    openRouterOnly: false,
    deprecated: true,
  },
  gpt54pro: {
    name: 'gpt54pro',
    label: 'GPT-5.4 Pro',
    fullName: 'gpt-5.4-pro-2026-03-05',
    shortName: 'gpt-5.4-pro',
    openrouterFullName: 'openai/gpt-5.4-pro',
    vscodeLMFullName: 'gpt-5.4-pro',
    provider: ModelProvider.OPENAI,
    maxOutputTokens: 128000,
    contextWindow: 1050000,
    inputPrice: 30.0,
    outputPrice: 180.0,
    capabilities: {
      ...OPENAI_REASONING_DEFAULT_CAPABILITIES,
      supportsAutoPromptCaching: false,
      supportsNativeMCPServer: true,
      supportsNativeWebSearch: true,
      supportsVision: true,
      supportsNativePdf: true,
      reasoningEffort: ReasoningEffort.XHIGH,
    },
    requiresResponsesAPI: true,
    openRouterOnly: false,
    deprecated: true,
  },
  gpt55: {
    name: 'gpt55',
    label: 'GPT-5.5',
    fullName: 'gpt-5.5-2026-04-23',
    shortName: 'gpt-5.5',
    openrouterFullName: 'openai/gpt-5.5',
    vscodeLMFullName: 'gpt-5.5',
    provider: ModelProvider.OPENAI,
    maxOutputTokens: 128000,
    contextWindow: 1050000,
    inputPrice: 5.0,
    outputPrice: 30.0,
    capabilities: {
      ...OPENAI_REASONING_DEFAULT_CAPABILITIES,
      cacheDiscountFactor: 0.1,
      reasoningEffort: ReasoningEffort.XHIGH,
      supportsNativeMCPServer: true,
      supportsNativeWebSearch: true,
      supportsNativeCodeExecution: true,
      supportsPredictiveOutput: true,
      supportsVision: true,
      supportsNativePdf: true,
    },
    openRouterOnly: false,
    codexSubscription: true,
    deprecated: true,
  },
  gpt55pro: {
    name: 'gpt55pro',
    label: 'GPT-5.5 Pro',
    fullName: 'gpt-5.5-pro-2026-04-23',
    shortName: 'gpt-5.5-pro',
    openrouterFullName: 'openai/gpt-5.5-pro',
    vscodeLMFullName: 'gpt-5.5-pro',
    provider: ModelProvider.OPENAI,
    maxOutputTokens: 128000,
    contextWindow: 1050000,
    inputPrice: 30.0,
    outputPrice: 180.0,
    capabilities: {
      ...OPENAI_REASONING_DEFAULT_CAPABILITIES,
      supportsAutoPromptCaching: false,
      supportsNativeMCPServer: true,
      supportsNativeWebSearch: true,
      supportsNativeCodeExecution: true,
      supportsVision: true,
      supportsNativePdf: true,
      reasoningEffort: ReasoningEffort.XHIGH,
    },
    requiresResponsesAPI: true,
    openRouterOnly: false,
    deprecated: true,
  },
  gpt56: {
    name: 'gpt56',
    label: 'GPT-5.6 Sol',
    fullName: 'gpt-5.6-sol',
    shortName: 'gpt-5.6',
    openrouterFullName: 'openai/gpt-5.6',
    vscodeLMFullName: 'gpt-5.6',
    provider: ModelProvider.OPENAI,
    maxOutputTokens: 128000,
    contextWindow: 1050000,
    // Promotional pricing (confirmed active through at least November 21,
    // 2026): $4.00 / $20.00, cut from the $5.00 / $30.00 launch rate.
    inputPrice: 4.0,
    outputPrice: 20.0,
    capabilities: {
      ...OPENAI_REASONING_DEFAULT_CAPABILITIES,
      cacheDiscountFactor: 0.1,
      reasoningEffort: ReasoningEffort.MEDIUM,
      maxReasoningEffort: ReasoningEffort.MAX,
      supportsPromptCaching: true,
      supportsNativeMCPServer: true,
      supportsNativeWebSearch: true,
      supportsNativeCodeExecution: true,
      supportsPredictiveOutput: true,
      supportsVision: true,
      supportsNativePdf: true,
    },
    openRouterOnly: false,
    codexSubscription: true,
  },
  // gpt56pro: GPT-5.6 Sol driven in the Responses API's pro reasoning mode
  // (`reasoning.mode: 'pro'`). Unlike earlier Pro releases this is not a
  // separate model id — the request targets gpt-5.6-sol, and pro mode bills
  // the aggregated work at the model's standard token rates, so pricing
  // matches the gpt56 entry. Responses-API only.
  gpt56pro: {
    name: 'gpt56pro',
    label: 'GPT-5.6 Pro',
    fullName: 'gpt-5.6-sol',
    // Not `gpt-5.6-pro`: pro mode is a request parameter, not a model id, so
    // the unpinned API name is the same one fullName targets.
    shortName: 'gpt-5.6-sol',
    provider: ModelProvider.OPENAI,
    maxOutputTokens: 128000,
    contextWindow: 1050000,
    // Same promotional rate as gpt56 — pro mode bills at Sol's standard
    // token rates (see the comment above).
    inputPrice: 4.0,
    outputPrice: 20.0,
    capabilities: {
      ...OPENAI_REASONING_DEFAULT_CAPABILITIES,
      cacheDiscountFactor: 0.1,
      reasoningEffort: ReasoningEffort.MEDIUM,
      maxReasoningEffort: ReasoningEffort.MAX,
      reasoningMode: 'pro',
      supportsPromptCaching: true,
      supportsNativeMCPServer: true,
      supportsNativeWebSearch: true,
      supportsNativeCodeExecution: true,
      supportsPredictiveOutput: true,
      supportsVision: true,
      supportsNativePdf: true,
    },
    requiresResponsesAPI: true,
    openRouterOnly: false,
  },
  // gpt56fast: GPT-5.6 Sol served in Fast mode (`service_tier: 'fast'`, the
  // 2026-07-30 rename of `'priority'`, which both remain accepted). Same model
  // id and same intelligence as gpt56 — up to 2.5x faster than Standard
  // processing at twice the Standard token rates. Cached-input discounts still
  // apply, so cacheDiscountFactor matches the standard-tier entry.
  // Fast mode is not Sol-only — the tier also serves Terra and Luna, whose
  // fast rates are published at a flat 2x like Sol's. Cataloging Sol alone is
  // a scoping choice (it is the tier that got the 2.5x speed-up), not a gap in
  // the source data.
  gpt56fast: {
    name: 'gpt56fast',
    label: 'GPT-5.6 Sol (Fast)',
    fullName: 'gpt-5.6-sol',
    shortName: 'gpt-5.6-sol',
    provider: ModelProvider.OPENAI,
    maxOutputTokens: 128000,
    contextWindow: 1050000,
    // Twice the current (promotional) standard-tier rate: $4.00 / $20.00.
    inputPrice: 8.0,
    outputPrice: 40.0,
    capabilities: {
      ...OPENAI_REASONING_DEFAULT_CAPABILITIES,
      cacheDiscountFactor: 0.1,
      reasoningEffort: ReasoningEffort.MEDIUM,
      maxReasoningEffort: ReasoningEffort.MAX,
      supportsPromptCaching: true,
      supportsNativeMCPServer: true,
      supportsNativeWebSearch: true,
      supportsNativeCodeExecution: true,
      supportsPredictiveOutput: true,
      supportsVision: true,
      supportsNativePdf: true,
    },
    serviceTier: 'fast',
    openRouterOnly: false,
  },
  'gpt56-': {
    name: 'gpt56-',
    label: 'GPT-5.6 Terra',
    fullName: 'gpt-5.6-terra',
    shortName: 'gpt-5.6-terra',
    openrouterFullName: 'openai/gpt-5.6-terra',
    vscodeLMFullName: 'gpt-5.6-terra',
    provider: ModelProvider.OPENAI,
    maxOutputTokens: 128000,
    contextWindow: 1050000,
    // 2026-07-30 price cut: 20% off the launch rates ($2.50 / $15).
    inputPrice: 2.0,
    outputPrice: 12.0,
    capabilities: {
      ...OPENAI_REASONING_DEFAULT_CAPABILITIES,
      cacheDiscountFactor: 0.1,
      reasoningEffort: ReasoningEffort.MEDIUM,
      maxReasoningEffort: ReasoningEffort.MAX,
      supportsPromptCaching: true,
      supportsNativeMCPServer: true,
      supportsNativeWebSearch: true,
      supportsNativeCodeExecution: true,
      supportsPredictiveOutput: true,
      supportsVision: true,
      supportsNativePdf: true,
    },
    openRouterOnly: false,
    codexSubscription: true,
  },
  'gpt56--': {
    name: 'gpt56--',
    label: 'GPT-5.6 Luna',
    fullName: 'gpt-5.6-luna',
    shortName: 'gpt-5.6-luna',
    openrouterFullName: 'openai/gpt-5.6-luna',
    provider: ModelProvider.OPENAI,
    maxOutputTokens: 128000,
    contextWindow: 1050000,
    // 2026-07-30 price cut: 80% off the launch rates ($1 / $6).
    inputPrice: 0.2,
    outputPrice: 1.2,
    capabilities: {
      ...OPENAI_REASONING_DEFAULT_CAPABILITIES,
      cacheDiscountFactor: 0.1,
      reasoningEffort: ReasoningEffort.MEDIUM,
      maxReasoningEffort: ReasoningEffort.MAX,
      supportsPromptCaching: true,
      supportsNativeMCPServer: true,
      supportsNativeWebSearch: true,
      supportsNativeCodeExecution: true,
      supportsPredictiveOutput: true,
      supportsVision: true,
      supportsNativePdf: true,
    },
    openRouterOnly: false,
    codexSubscription: true,
  },
  // GPT-6 Astra (2026-09-04): OpenAI's flagship. Launched in the Trusted
  // Access Program, then opened the same day to Pro, Enterprise, and Business
  // Premium in ChatGPT Work and Codex, plus the API (Plus/Business followed
  // days later). Rate card: $10.00 input / $1.00 cached input / $12.50 cache
  // writes / $50.00 output per 1M; prompts over 272K input tokens bill the
  // full request at 2x input/cache and 1.5x output (the registry has no
  // long-context tier field, so the standard rates are cataloged here).
  // `reasoning.effort` accepts low/medium/high/xhigh/max.
  gpt6: {
    name: 'gpt6',
    label: 'GPT-6 Astra',
    fullName: 'gpt-6-astra',
    shortName: 'gpt-6-astra',
    provider: ModelProvider.OPENAI,
    maxOutputTokens: 128000,
    contextWindow: 1050000,
    inputPrice: 10.0,
    outputPrice: 50.0,
    capabilities: {
      ...OPENAI_REASONING_DEFAULT_CAPABILITIES,
      cacheDiscountFactor: 0.1,
      reasoningEffort: ReasoningEffort.MEDIUM,
      maxReasoningEffort: ReasoningEffort.MAX,
      supportsPromptCaching: true,
      supportsNativeMCPServer: true,
      supportsNativeWebSearch: true,
      supportsNativeCodeExecution: true,
      supportsVision: true,
    },
    // Responses API is required for the xhigh/max effort tiers; also keeps
    // coauthor's router (which only pattern-matches gpt-5* names) on the
    // Responses handler.
    requiresResponsesAPI: true,
    openRouterOnly: false,
    codexSubscription: true,
  },
  // gpt6fast: GPT-6 Astra served in Fast mode (`service_tier: 'fast'`) — up to
  // 2x the speed of Standard processing at exactly 2x the Standard token
  // rates, per developers.openai.com/api/docs/pricing. Same model id and
  // effort vocabulary as gpt6, so cacheDiscountFactor (cached input is still
  // 10% of input) carries over unchanged.
  gpt6fast: {
    name: 'gpt6fast',
    label: 'GPT-6 Astra (Fast)',
    fullName: 'gpt-6-astra',
    shortName: 'gpt-6-astra',
    provider: ModelProvider.OPENAI,
    maxOutputTokens: 128000,
    contextWindow: 1050000,
    inputPrice: 20.0,
    outputPrice: 100.0,
    capabilities: {
      ...OPENAI_REASONING_DEFAULT_CAPABILITIES,
      cacheDiscountFactor: 0.1,
      reasoningEffort: ReasoningEffort.MEDIUM,
      maxReasoningEffort: ReasoningEffort.MAX,
      supportsPromptCaching: true,
      supportsNativeMCPServer: true,
      supportsNativeWebSearch: true,
      supportsNativeCodeExecution: true,
      supportsVision: true,
    },
    requiresResponsesAPI: true,
    serviceTier: 'fast',
    openRouterOnly: false,
  },
  gpt54: {
    name: 'gpt54',
    label: 'GPT-5.4',
    fullName: 'gpt-5.4-2026-03-05',
    shortName: 'gpt-5.4',
    openrouterFullName: 'openai/gpt-5.4',
    vscodeLMFullName: 'gpt-5.4',
    copilotFullName: 'gpt-5.4',
    provider: ModelProvider.OPENAI,
    maxOutputTokens: 128000,
    contextWindow: 1050000,
    inputPrice: 2.5,
    outputPrice: 15.0,
    capabilities: {
      ...OPENAI_REASONING_DEFAULT_CAPABILITIES,
      cacheDiscountFactor: 0.1,
      reasoningEffort: ReasoningEffort.XHIGH,
      supportsNativeMCPServer: true,
      supportsNativeWebSearch: true,
      supportsNativeCodeExecution: true,
      supportsPredictiveOutput: true,
      supportsVision: true,
      supportsNativePdf: true,
    },
    openRouterOnly: false,
    codexSubscription: true,
    deprecated: true,
  },
  'gpt54-': {
    name: 'gpt54-',
    label: 'GPT-5.4 Mini',
    fullName: 'gpt-5.4-mini-2026-03-17',
    shortName: 'gpt-5.4-mini',
    openrouterFullName: 'openai/gpt-5.4-mini',
    vscodeLMFullName: 'gpt-5.4-mini',
    provider: ModelProvider.OPENAI,
    maxOutputTokens: 128000,
    contextWindow: 400000,
    inputPrice: 0.75,
    outputPrice: 4.5,
    capabilities: {
      ...OPENAI_REASONING_DEFAULT_CAPABILITIES,
      cacheDiscountFactor: 0.1,
      reasoningEffort: ReasoningEffort.XHIGH,
      supportsNativeMCPServer: true,
      supportsNativeWebSearch: true,
      supportsNativeCodeExecution: true,
      supportsPredictiveOutput: true,
      supportsVision: true,
      supportsNativePdf: true,
    },
    openRouterOnly: false,
    codexSubscription: true,
    deprecated: true,
  },
  'gpt54--': {
    name: 'gpt54--',
    label: 'GPT-5.4 Nano',
    fullName: 'gpt-5.4-nano-2026-03-17',
    shortName: 'gpt-5.4-nano',
    openrouterFullName: 'openai/gpt-5.4-nano',
    provider: ModelProvider.OPENAI,
    maxOutputTokens: 128000,
    contextWindow: 400000,
    inputPrice: 0.2,
    outputPrice: 1.25,
    capabilities: {
      ...OPENAI_REASONING_DEFAULT_CAPABILITIES,
      cacheDiscountFactor: 0.1,
      reasoningEffort: ReasoningEffort.XHIGH,
      supportsNativeMCPServer: true,
      supportsNativeWebSearch: true,
      supportsNativeCodeExecution: true,
      supportsVision: true,
      supportsNativePdf: true,
    },
    openRouterOnly: false,
    deprecated: true,
  },
  'gpt5-': {
    name: 'gpt5-',
    label: 'GPT-5 Mini',
    fullName: 'gpt-5-mini-2025-08-07',
    shortName: 'gpt-5-mini',
    openrouterFullName: 'openai/gpt-5-mini-2025-08-07',
    vscodeLMFullName: 'gpt-5-mini',
    provider: ModelProvider.OPENAI,
    maxOutputTokens: 128000,
    contextWindow: 400000,
    inputPrice: 0.25,
    outputPrice: 2.0,
    capabilities: {
      ...OPENAI_REASONING_DEFAULT_CAPABILITIES,
      cacheDiscountFactor: 0.1,
      supportsNativeMCPServer: true,
      supportsNativeWebSearch: true,
      supportsNativeCodeExecution: true,
      supportsPredictiveOutput: true,
      supportsVision: true,
      supportsNativePdf: true,
    },
    openRouterOnly: false,
    deprecated: true,
  },
  'gpt5--': {
    name: 'gpt5--',
    label: 'GPT-5 Nano',
    fullName: 'gpt-5-nano-2025-08-07',
    shortName: 'gpt-5-nano',
    openrouterFullName: 'openai/gpt-5-nano-2025-08-07',
    provider: ModelProvider.OPENAI,
    maxOutputTokens: 128000,
    contextWindow: 400000,
    inputPrice: 0.05,
    outputPrice: 0.4,
    capabilities: {
      ...OPENAI_REASONING_DEFAULT_CAPABILITIES,
      cacheDiscountFactor: 0.1,
      supportsNativeMCPServer: true,
      supportsNativeWebSearch: true,
      supportsNativeCodeExecution: true,
      supportsPredictiveOutput: true,
      supportsVision: true,
      supportsNativePdf: true,
    },
    openRouterOnly: false,
    deprecated: true,
  },
};
